; ============================================================
; src/WIN/seg1_real.asm  --  AUTO-GENERATED by
;   bootstrap/disasm_to_masm.py
;
; Byte-exact MASM 4.00 source for original/WIN.COM (4873 B). The
; bulk of executable code appears as real instructions; only
; instructions whose MASM 4.00 encoding differs from the shipped
; bytes (or which cross-reference data in opaque ways) fall back
; to `db <bytes>` directives. This file is verified byte-exact
; via bootstrap/analyze/verify_flat_com_via_masm.py.
; ============================================================

        .8086
WIN_SEG1 SEGMENT BYTE PUBLIC 'CODE'
        ASSUME cs:WIN_SEG1, ds:WIN_SEG1, ss:WIN_SEG1, es:WIN_SEG1

; -- data 0x0000..0x01C0 (449B) --
        db 0E9h, 0BEh, 01h, 00h, 35h, 00h, 00h, 00h, 00h, 49h, 6Eh, 73h, 65h, 72h, 74h, 20h
d_0010: db 'DOS$Insert Application$Insert Windows Startup$ disk in drive'
        db ' x:'
        db 0Dh, 0Ah, 50h, 72h, 65h, 73h, 73h, 20h, 61h, 6Eh, 79h, 20h, 6Bh, 65h, 79h, 20h
d_005F: db 'when ready $'
        db 0Dh, 0Ah, 0Dh, 0Ah, 24h, 50h, 72h, 6Fh, 67h, 72h, 61h, 6Dh, 20h, 74h, 6Fh, 6Fh
d_007B: db ' big to fit in memory'
        db 00h, 4Eh, 6Fh, 74h, 20h, 65h, 6Eh, 6Fh, 75h, 67h, 68h, 20h, 64h, 69h, 73h, 6Bh
d_00A0: db ' space for screen exchange'
        db 00h, 43h, 61h, 6Eh, 6Eh, 6Fh, 74h, 20h, 66h, 69h, 6Eh, 64h, 20h, 57h, 69h, 6Eh
d_00CA: db 'dows startup files'
        db 00h, 41h, 3Ah, 5Ch, 43h, 4Fh, 4Dh, 4Dh, 41h, 4Eh, 44h, 2Eh, 43h, 4Fh, 4Dh, 00h
d_00EC: db 'COMSPEC='
        db 00h, 50h, 41h, 54h, 48h, 3Dh, 00h, 57h, 49h, 4Eh, 31h, 30h, 30h, 2Eh, 42h, 49h
        db 4Eh, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 5Ch, 78h, 63h, 68h, 67h, 2Eh, 24h, 24h, 24h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
L_01C1:   mov       sp, 890h                         ; [BC 90 08]
          db 0E8h, 83h, 04h                                   ; call 0x74a
          db 0E8h, 19h, 04h                                   ; call 0x6e3
          mov       word ptr ds:[100h], 27Ah         ; [C7 06 00 01 7A 02]
          mov       ah, 30h                          ; [B4 30]
          int       21h                              ; [CD 21]
          mov       byte ptr ds:[262h], al           ; [A2 62 02]
L_01D7:   db 0E8h, 0CCh, 03h                                  ; call 0x6a6
L_01DA:   mov       ax, 5758h                        ; [B8 58 57]
L_01DD:   mov       word ptr ds:[263h], ax           ; [A3 63 02]
          mov       byte ptr ds:[281h], 0            ; [C6 06 81 02 00]
          db 0E8h, 32h, 01h                                   ; call 0x41a
          pushf                                      ; [9C]
          push      ax                               ; [50]
          db 0E8h, 58h, 04h                                   ; call 0x745
          pop       ax                               ; [58]
          popf                                       ; [9D]
          jae       L_021A                           ; [73 29]
          cmp       byte ptr ds:[269h], 0            ; [80 3E 69 02 00]
          jne       L_0209                           ; [75 11]
          cmp       al, 8                            ; [3C 08]
          jne       L_0201                           ; [75 05]
          db 0E8h, 0DFh, 00h                                  ; call 0x3de
          int       20h                              ; [CD 20]
L_0201:   mov       si, 1BBh                         ; [BE BB 01]
          db 0E8h, 0DAh, 00h                                  ; call 0x3e1
          int       20h                              ; [CD 20]
L_0209:   cmp       al, 8                            ; [3C 08]
          jne       L_0212                           ; [75 05]
          db 0E8h, 44h, 03h                                   ; call 0x654
          jmp       short L_01D7                     ; [EB C5]
L_0212:   db 0E8h, 0C5h, 01h                                  ; call 0x4da
          db 0E8h, 0E2h, 00h                                  ; call 0x3fa
          jmp       short L_01D7                     ; [EB BD]
L_021A:   mov       byte ptr ds:[269h], 1            ; [C6 06 69 02 01]
          cmp       byte ptr ds:[281h], 0            ; [80 3E 81 02 00]
          jne       L_0229                           ; [75 03]
          db 0E9h, 96h, 00h                                   ; jmp 0x3bf
L_0229:   db 0E8h, 75h, 02h                                   ; call 0x5a1
          mov       ax, word ptr ds:[27Eh]           ; [A1 7E 02]
          or        ax, ax                           ; [0B C0]
          je        L_0242                           ; [74 0F]
          mov       si, 0                            ; [BE 00 00]
          db 0E8h, 8Ch, 02h                                   ; call 0x5c5
          db 0E8h, 99h, 02h                                   ; call 0x5d5
          mov       si, 3                            ; [BE 03 00]
          db 0E8h, 83h, 02h                                   ; call 0x5c5
L_0242:   mov       dx, 281h                         ; [BA 81 02]
          db 0E8h, 2Eh, 01h                                   ; call 0x476
          jae       L_026C                           ; [73 22]
          cmp       ax, 2                            ; [3D 02 00]
          jne       L_025A                           ; [75 0B]
          mov       dx, 114h                         ; [BA 14 01]
          mov       si, 281h                         ; [BE 81 02]
          db 0E8h, 0A5h, 00h                                  ; call 0x3fd
          jmp       short L_0242                     ; [EB E8]
L_025A:   cmp       ax, 8                            ; [3D 08 00]
          jne       L_026B                           ; [75 0C]
          cmp       byte ptr ds:[262h], 3            ; [80 3E 62 02 03]
          jae       L_026B                           ; [73 05]
          db 0E8h, 0EBh, 02h                                  ; call 0x654
          jmp       short L_0242                     ; [EB D7]
L_026B:   stc                                        ; [F9]
L_026C:   mov       word ptr ds:[80h], 0D00h         ; [C7 06 80 00 00 0D]
          pushf                                      ; [9C]
          cmp       word ptr ds:[27Eh], 0            ; [83 3E 7E 02 00]
          je        L_0280                           ; [74 06]
          mov       si, 6                            ; [BE 06 00]
          db 0E8h, 45h, 02h                                   ; call 0x5c5
L_0280:   popf                                       ; [9D]
          jae       L_0289                           ; [73 06]
          db 0E8h, 58h, 00h                                   ; call 0x3de
          db 0E9h, 51h, 0FFh                                  ; jmp 0x2da
L_0289:   db 0E8h, 0BBh, 02h                                  ; call 0x647
          mov       si, 9                            ; [BE 09 00]
          mov       ax, si                           ; [8B C6]
          jcxz      L_0295                           ; [E3 02]
          xor       ax, ax                           ; [33 C0]
L_0295:   test      byte ptr ds:[280h], 10h          ; [F6 06 80 02 10]
          jne       L_029F                           ; [75 03]
          db 0E8h, 26h, 02h                                   ; call 0x5c5
L_029F:   db 0E8h, 6Eh, 02h                                   ; call 0x610
          pushf                                      ; [9C]
          push      cx                               ; [51]
          db 0E8h, 53h, 02h                                   ; call 0x5fa
          db 0E8h, 9Bh, 03h                                   ; call 0x745
          pop       cx                               ; [59]
          popf                                       ; [9D]
          jb        L_02B4                           ; [72 06]
          mov       ax, 5747h                        ; [B8 47 57]
          db 0E9h, 29h, 0FFh                                  ; jmp 0x2dd
L_02B4:   jcxz      L_02BC                           ; [E3 06]
          mov       si, 191h                         ; [BE 91 01]
          db 0E8h, 25h, 00h                                   ; call 0x3e1
L_02BC:   db 0E9h, 1Bh, 0FFh                                  ; jmp 0x2da
L_02BF:   mov       dx, 258h                         ; [BA 58 02]
          mov       ah, 41h                          ; [B4 41]
          int       21h                              ; [CD 21]
          mov       si, 6E3h                         ; [BE E3 06]
          db 0E8h, 11h, 01h                                   ; call 0x4dd
          mov       dx, si                           ; [8B D6]
          mov       ah, 3Bh                          ; [B4 3B]
          int       21h                              ; [CD 21]
          mov       ah, 4Dh                          ; [B4 4D]
          int       21h                              ; [CD 21]
          mov       ah, 4Ch                          ; [B4 4C]
          int       21h                              ; [CD 21]
          cmp       al, 8                            ; [3C 08]
          jne       L_02E1                           ; [75 03]
L_02DE:   mov       si, 170h                         ; [BE 70 01]
L_02E1:   lodsb                                      ; [AC]
          or        al, al                           ; [0A C0]
          je        L_02EE                           ; [74 08]
          mov       dl, al                           ; [8A D0]
          mov       ah, 2                            ; [B4 02]
          int       21h                              ; [CD 21]
          jmp       short L_02E1                     ; [EB F3]
L_02EE:   mov       dl, 0Dh                          ; [B2 0D]
          db 0E8h, 02h, 00h                                   ; call 0x3f5
          mov       dl, 0Ah                          ; [B2 0A]
L_02F5:   mov       ah, 2                            ; [B4 02]
          int       21h                              ; [CD 21]
          ret                                        ; [C3]
L_02FA:   mov       dx, 127h                         ; [BA 27 01]
L_02FD:   mov       ax, word ptr [si]                ; [8B 04]
          mov       byte ptr ds:[14Dh], al           ; [A2 4D 01]
L_0302:   mov       ah, 9                            ; [B4 09]
          int       21h                              ; [CD 21]
          mov       dx, 13Eh                         ; [BA 3E 01]
          mov       ah, 9                            ; [B4 09]
          int       21h                              ; [CD 21]
          mov       ax, 0C08h                        ; [B8 08 0C]
          int       21h                              ; [CD 21]
          mov       dx, 16Bh                         ; [BA 6B 01]
          mov       ah, 9                            ; [B4 09]
          int       21h                              ; [CD 21]
          ret                                        ; [C3]
L_031A:   cld                                        ; [FC]
          push      ss                               ; [16]
          pop       es                               ; [07]
          mov       ax, word ptr ds:[263h]           ; [A1 63 02]
          mov       word ptr ds:[0FEh], ax           ; [A3 FE 00]
          mov       si, 1FBh                         ; [BE FB 01]
          mov       cx, 0Dh                          ; [B9 0D 00]
          cmp       byte ptr ds:[269h], 0            ; [80 3E 69 02 00]
          je        L_033E                           ; [74 0E]
          mov       si, 206h                         ; [BE 06 02]
          mov       di, si                           ; [8B FE]
          mov       cx, 0FFFFh                       ; [B9 FF FF]
          xor       ax, ax                           ; [33 C0]
          repne scasb                                 ; [F2 AE]
          not       cx                               ; [F7 D1]
L_033E:   mov       di, 80h                          ; [BF 80 00]
          xor       ax, ax                           ; [33 C0]
          mov       al, byte ptr [di]                ; [8A 05]
          add       al, cl                           ; [02 C1]
          add       ax, 3                            ; [05 03 00]
          sub       ax, 7Eh                          ; [2D 7E 00]
          jle       L_0351                           ; [7E 02]
          sub       byte ptr [di], al                ; [28 05]
L_0351:   xor       ax, ax                           ; [33 C0]
          mov       al, byte ptr [di]                ; [8A 05]
          inc       di                               ; [47]
          add       di, ax                           ; [03 F8]
          mov       al, 0Dh                          ; [B0 0D]
          stosb                                      ; [AA]
          mov       ax, cx                           ; [8B C1]
          stosb                                      ; [AA]
          cmp       byte ptr ds:[269h], 0            ; [80 3E 69 02 00]
          jne       L_0371                           ; [75 0C]
          mov       ah, 19h                          ; [B4 19]
          int       21h                              ; [CD 21]
          add       al, 41h                          ; [04 41]
          mov       ah, 3Ah                          ; [B4 3A]
          stosw                                      ; [AB]
          sub       cx, 2                            ; [83 E9 02]
L_0371:   rep movsb                                  ; [F3 A4]
          mov       dx, 206h                         ; [BA 06 02]
L_0376:   mov       ax, ds                           ; [8C D8]
          mov       es, ax                           ; [8E C0]
          mov       word ptr ds:[26Ch], 80h          ; [C7 06 6C 02 80 00]
          mov       word ptr ds:[26Eh], ds           ; [8C 1E 6E 02]
          mov       word ptr ds:[270h], 5Ch          ; [C7 06 70 02 5C 00]
          mov       word ptr ds:[272h], ds           ; [8C 1E 72 02]
          mov       word ptr ds:[274h], 6Ch          ; [C7 06 74 02 6C 00]
          mov       word ptr ds:[276h], ds           ; [8C 1E 76 02]
          mov       si, 81h                          ; [BE 81 00]
          mov       di, 5Ch                          ; [BF 5C 00]
          mov       ax, 2901h                        ; [B8 01 29]
          int       21h                              ; [CD 21]
          mov       di, 6Ch                          ; [BF 6C 00]
          mov       ax, 2901h                        ; [B8 01 29]
          int       21h                              ; [CD 21]
          mov       bx, 26Ah                         ; [BB 6A 02]
          push      ds                               ; [1E]
          pop       es                               ; [07]
          mov       ax, word ptr ds:[2Ch]            ; [A1 2C 00]
          mov       word ptr [bx], ax                ; [89 07]
          push      ds                               ; [1E]
          push      dx                               ; [52]
          push      es                               ; [06]
          push      bx                               ; [53]
          db 0E8h, 2Bh, 00h                                   ; call 0x4e7
          ret                                        ; [C3]
; -- data 0x03BD..0x03D9 (29B) --
        db 0E8h, 1Ah, 00h, 56h, 0ACh, 0Ah, 0C0h, 75h, 0FBh, 0B1h, 5Ch, 4Eh, 38h, 0Ch, 75h, 0FBh
        db 0C6h, 04h, 00h, 5Ah, 0B4h, 3Bh, 0CDh, 21h, 88h, 0Ch, 8Bh, 0F2h, 0C3h
L_03DA:   mov       si, 206h                         ; [BE 06 02]
L_03DD:   mov       dl, byte ptr [si]                ; [8A 14]
          sub       dl, 41h                          ; [80 EA 41]
          mov       ah, 0Eh                          ; [B4 0E]
          int       21h                              ; [CD 21]
          ret                                        ; [C3]
L_03E7:   push      bp                               ; [55]
          mov       bp, sp                           ; [8B EC]
          sub       sp, 54h                          ; [83 EC 54]
          push      ds                               ; [1E]
          cld                                        ; [FC]
          db 0C5h, 76h, 08h                                   ; (force-db) lds si, ptr [bp + 8]
          push      ss                               ; [16]
          pop       es                               ; [07]
          lea       di, [bp - 52h]                   ; [8D 7E AE]
          mov       bx, di                           ; [8B DF]
L_03F9:   lodsb                                      ; [AC]
          cmp       al, 2Fh                          ; [3C 2F]
          je        L_0406                           ; [74 08]
          cmp       al, 5Ch                          ; [3C 5C]
          je        L_0406                           ; [74 04]
          cmp       al, 3Ah                          ; [3C 3A]
          jne       L_0409                           ; [75 03]
L_0406:   mov       bx, di                           ; [8B DF]
          inc       bx                               ; [43]
L_0409:   stosb                                      ; [AA]
          or        al, al                           ; [0A C0]
          jne       L_03F9                           ; [75 EB]
          mov       word ptr [bp - 54h], bx          ; [89 5E AC]
          db 0C5h, 56h, 08h                                   ; (force-db) lds dx, ptr [bp + 8]
          db 0C4h, 5Eh, 04h                                   ; (force-db) les bx, ptr [bp + 4]
          db 0E8h, 68h, 00h                                   ; call 0x582
          jae       L_047B                           ; [73 5F]
          cmp       al, 2                            ; [3C 02]
          je        L_0424                           ; [74 04]
          cmp       al, 3                            ; [3C 03]
          jne       L_047A                           ; [75 56]
L_0424:   db 0E8h, 5Bh, 01h                                   ; call 0x682
          jne       L_047A                           ; [75 51]
L_0429:   db 0C4h, 7Eh, 08h                                   ; (force-db) les di, ptr [bp + 8]
          cmp       byte ptr [si + 1], 3Ah           ; [80 7C 01 3A]
          je        L_043B                           ; [74 09]
          mov       ah, 19h                          ; [B4 19]
          int       21h                              ; [CD 21]
          add       al, 41h                          ; [04 41]
          mov       ah, 3Ah                          ; [B4 3A]
          stosw                                      ; [AB]
L_043B:   lodsb                                      ; [AC]
          stosb                                      ; [AA]
          cmp       al, 3Bh                          ; [3C 3B]
          je        L_0446                           ; [74 05]
          or        al, al                           ; [0A C0]
          jne       L_043B                           ; [75 F6]
          dec       si                               ; [4E]
L_0446:   mov       al, 5Ch                          ; [B0 5C]
          cmp       byte ptr es:[di - 2], al         ; [26 38 45 FE]
          jne       L_044F                           ; [75 01]
          dec       di                               ; [4F]
L_044F:   mov       byte ptr es:[di - 1], al         ; [26 88 45 FF]
          push      ds                               ; [1E]
          push      si                               ; [56]
          push      ss                               ; [16]
          pop       ds                               ; [1F]
          mov       si, word ptr [bp - 54h]          ; [8B 76 AC]
L_045A:   lodsb                                      ; [AC]
          stosb                                      ; [AA]
          or        al, al                           ; [0A C0]
          jne       L_045A                           ; [75 FA]
          db 0C5h, 56h, 08h                                   ; (force-db) lds dx, ptr [bp + 8]
          db 0C4h, 5Eh, 04h                                   ; (force-db) les bx, ptr [bp + 4]
          db 0E8h, 19h, 00h                                   ; call 0x582
          pop       si                               ; [5E]
          pop       ds                               ; [1F]
          jae       L_047B                           ; [73 0E]
          cmp       al, 2                            ; [3C 02]
          je        L_0475                           ; [74 04]
          cmp       al, 3                            ; [3C 03]
          jne       L_047A                           ; [75 05]
L_0475:   cmp       byte ptr [si], 0                 ; [80 3C 00]
          jne       L_0429                           ; [75 AF]
L_047A:   stc                                        ; [F9]
L_047B:   pop       ds                               ; [1F]
          mov       sp, bp                           ; [8B E5]
          pop       bp                               ; [5D]
          ret       8                                ; [C2 08 00]
L_0482:   clc                                        ; [F8]
          push      ds                               ; [1E]
          push      bp                               ; [55]
          mov       word ptr cs:[105h], ss           ; [2E 8C 16 05 01]
          mov       word ptr cs:[107h], sp           ; [2E 89 26 07 01]
          mov       ax, 4B00h                        ; [B8 00 4B]
          int       21h                              ; [CD 21]
          mov       ss, word ptr cs:[105h]           ; [2E 8E 16 05 01]
          mov       sp, word ptr cs:[107h]           ; [2E 8B 26 07 01]
          pop       bp                               ; [5D]
          pop       ds                               ; [1F]
          ret                                        ; [C3]
L_04A1:   push      es                               ; [06]
          push      ds                               ; [1E]
          mov       bx, word ptr ds:[27Ch]           ; [8B 1E 7C 02]
          mov       cx, bx                           ; [8B CB]
          mov       ah, 48h                          ; [B4 48]
          int       21h                              ; [CD 21]
          mov       es, ax                           ; [8E C0]
          xchg      word ptr ds:[27Ah], ax           ; [87 06 7A 02]
          mov       ds, ax                           ; [8E D8]
          xor       si, si                           ; [33 F6]
          xor       di, di                           ; [33 FF]
          shl       cx, 1                            ; [D1 E1]
          shl       cx, 1                            ; [D1 E1]
          shl       cx, 1                            ; [D1 E1]
          cld                                        ; [FC]
          rep movsw                                  ; [F3 A5]
          pop       ds                               ; [1F]
          pop       es                               ; [07]
          ret                                        ; [C3]
L_04C5:   push      ds                               ; [1E]
          mov       word ptr ds:[278h], si           ; [89 36 78 02]
          mov       ds, word ptr ds:[27Ah]           ; [8E 1E 7A 02]
          db 36h, 0FFh, 1Eh, 78h, 02h                         ; (force-db) lcall ss:[0x278]
          pop       ds                               ; [1F]
          ret                                        ; [C3]
L_04D5:   push      ax                               ; [50]
          add       ax, 0Fh                          ; [05 0F 00]
          mov       cl, 4                            ; [B1 04]
          shr       ax, cl                           ; [D3 E8]
          mov       bx, ax                           ; [8B D8]
          mov       ah, 48h                          ; [B4 48]
          int       21h                              ; [CD 21]
          jb        L_04F9                           ; [72 14]
          mov       es, ax                           ; [8E C0]
          xor       di, di                           ; [33 FF]
          xor       ax, ax                           ; [33 C0]
          mov       word ptr ds:[265h], ax           ; [A3 65 02]
          mov       word ptr ds:[267h], es           ; [8C 06 67 02]
          stosw                                      ; [AB]
          stosw                                      ; [AB]
          pop       ax                               ; [58]
          xor       dx, dx                           ; [33 D2]
          mov       di, dx                           ; [8B FA]
L_04F9:   ret                                        ; [C3]
L_04FA:   mov       cx, word ptr ds:[267h]           ; [8B 0E 67 02]
          jcxz      L_0503                           ; [E3 03]
          db 0E8h, 06h, 00h                                   ; call 0x609
L_0503:   mov       cx, word ptr ds:[27Ah]           ; [8B 0E 7A 02]
          jcxz      L_050F                           ; [E3 06]
L_0509:   mov       es, cx                           ; [8E C1]
          mov       ah, 49h                          ; [B4 49]
          int       21h                              ; [CD 21]
L_050F:   ret                                        ; [C3]
L_0510:   db 0E8h, 34h, 00h                                   ; call 0x647
          jcxz      L_053E                           ; [E3 29]
          push      ds                               ; [1E]
          db 0E8h, 0C1h, 0FEh                                 ; call 0x4da
          mov       dx, 258h                         ; [BA 58 02]
          xor       cx, cx                           ; [33 C9]
          mov       ah, 3Ch                          ; [B4 3C]
          int       21h                              ; [CD 21]
          jb        L_053A                           ; [72 16]
          mov       bx, ax                           ; [8B D8]
          db 0C5h, 16h, 65h, 02h                              ; (force-db) lds dx, ptr [0x265]
          mov       di, dx                           ; [8B FA]
          mov       cx, word ptr [di + 2]            ; [8B 4D 02]
          add       cx, 4                            ; [83 C1 04]
          mov       ah, 40h                          ; [B4 40]
          int       21h                              ; [CD 21]
          mov       ah, 3Eh                          ; [B4 3E]
          int       21h                              ; [CD 21]
L_053A:   pop       ds                               ; [1F]
          mov       cl, 1                            ; [B1 01]
          ret                                        ; [C3]
L_053E:   mov       dx, 258h                         ; [BA 58 02]
          mov       ah, 41h                          ; [B4 41]
          int       21h                              ; [CD 21]
          stc                                        ; [F9]
          ret                                        ; [C3]
L_0547:   db 0C4h, 3Eh, 65h, 02h                              ; (force-db) les di, ptr [0x265]
          mov       cx, es                           ; [8C C1]
          jcxz      L_0553                           ; [E3 04]
          mov       cx, word ptr es:[di + 2]         ; [26 8B 4D 02]
L_0553:   ret                                        ; [C3]
L_0554:   mov       di, 1ECh                         ; [BF EC 01]
          mov       cx, 8                            ; [B9 08 00]
          db 0E8h, 2Bh, 00h                                   ; call 0x688
          je        L_0564                           ; [74 05]
          push      cs                               ; [0E]
          pop       ds                               ; [1F]
          mov       si, 1DDh                         ; [BE DD 01]
L_0564:   mov       di, ds                           ; [8C DF]
          mov       ax, word ptr [si]                ; [8B 04]
          mov       byte ptr cs:[14Dh], al           ; [2E A2 4D 01]
L_056C:   mov       ds, di                           ; [8E DF]
          mov       dx, si                           ; [8B D6]
          mov       ax, 4300h                        ; [B8 00 43]
          int       21h                              ; [CD 21]
          push      cs                               ; [0E]
          pop       ds                               ; [1F]
          jae       L_0581                           ; [73 08]
          mov       dx, 109h                         ; [BA 09 01]
          db 0E8h, 83h, 0FDh                                  ; call 0x402
          jmp       short L_056C                     ; [EB EB]
L_0581:   ret                                        ; [C3]
L_0582:   mov       di, 1F5h                         ; [BF F5 01]
          mov       cx, 5                            ; [B9 05 00]
L_0588:   push      ss                               ; [16]
          pop       es                               ; [07]
          mov       ds, word ptr es:[2Ch]            ; [26 8E 1E 2C 00]
          xor       si, si                           ; [33 F6]
L_0591:   push      cx                               ; [51]
          push      di                               ; [57]
          repe cmpsb                                 ; [F3 A6]
          pop       di                               ; [5F]
          pop       cx                               ; [59]
          je        L_05A5                           ; [74 0C]
L_0599:   lodsb                                      ; [AC]
          or        al, al                           ; [0A C0]
          jne       L_0599                           ; [75 FB]
          cmp       byte ptr [si], 0                 ; [80 3C 00]
          jne       L_0591                           ; [75 EE]
          or        cx, cx                           ; [0B C9]
L_05A5:   ret                                        ; [C3]
L_05A6:   cld                                        ; [FC]
          push      ds                               ; [1E]
          pop       es                               ; [07]
          mov       di, 206h                         ; [BF 06 02]
          mov       ah, 19h                          ; [B4 19]
          int       21h                              ; [CD 21]
          add       al, 41h                          ; [04 41]
          stosb                                      ; [AA]
          mov       ax, 5C3Ah                        ; [B8 3A 5C]
          stosw                                      ; [AB]
          mov       si, di                           ; [8B F7]
          xor       dx, dx                           ; [33 D2]
          mov       ah, 47h                          ; [B4 47]
          int       21h                              ; [CD 21]
          mov       si, 206h                         ; [BE 06 02]
          mov       di, 6E3h                         ; [BF E3 06]
L_05C5:   lodsb                                      ; [AC]
          stosb                                      ; [AA]
          or        al, al                           ; [0A C0]
          jne       L_05C5                           ; [75 FA]
          mov       al, 5Ch                          ; [B0 5C]
          cmp       byte ptr [si - 2], al            ; [38 44 FE]
          jne       L_05D3                           ; [75 01]
          dec       si                               ; [4E]
L_05D3:   mov       byte ptr [si - 1], al            ; [88 44 FF]
          mov       di, si                           ; [8B FE]
          mov       si, 1FBh                         ; [BE FB 01]
L_05DB:   lodsb                                      ; [AC]
          stosb                                      ; [AA]
          or        al, al                           ; [0A C0]
          jne       L_05DB                           ; [75 FA]
          clc                                        ; [F8]
          ret                                        ; [C3]
L_05E3:   add       ax, 89Fh                         ; [05 9F 08]
          mov       cl, 4                            ; [B1 04]
          shr       ax, cl                           ; [D3 E8]
          mov       bx, ax                           ; [8B D8]
          push      ss                               ; [16]
          pop       es                               ; [07]
          mov       ah, 4Ah                          ; [B4 4A]
          int       21h                              ; [CD 21]
          mov       bx, 0FFFFh                       ; [BB FF FF]
          mov       ah, 48h                          ; [B4 48]
          int       21h                              ; [CD 21]
          cmp       bx, word ptr cs:[103h]           ; [2E 3B 1E 03 01]
          jae       L_0609                           ; [73 09]
          db 0E8h, 42h, 00h                                   ; call 0x745
          db 0E8h, 0D8h, 0FCh                                 ; call 0x3de
          db 0E9h, 0B6h, 0FCh                                 ; jmp 0x3bf
L_0609:   cmp       word ptr cs:[81h], 2120h         ; [2E 81 3E 81 00 20 21]
          jne       L_0644                           ; [75 32]
          sub       bx, word ptr cs:[103h]           ; [2E 2B 1E 03 01]
          mov       byte ptr cs:[82h], 20h           ; [2E C6 06 82 00 20]
          xor       ax, ax                           ; [33 C0]
          mov       al, byte ptr cs:[83h]            ; [2E A0 83 00]
          sub       al, 30h                          ; [2C 30]
          cmp       al, 9                            ; [3C 09]
          ja        L_0640                           ; [77 17]
          mov       byte ptr cs:[83h], 20h           ; [2E C6 06 83 00 20]
          mov       cl, 0Ch                          ; [B1 0C]
          shl       ax, cl                           ; [D3 E0]
          or        ax, ax                           ; [0B C0]
          jne       L_063A                           ; [75 03]
          mov       ax, 400h                         ; [B8 00 04]
L_063A:   cmp       ax, bx                           ; [3B C3]
          jae       L_0644                           ; [73 06]
          sub       bx, ax                           ; [2B D8]
L_0640:   mov       ah, 48h                          ; [B4 48]
          int       21h                              ; [CD 21]
L_0644:   ret                                        ; [C3]
L_0645:   mov       di, 7                            ; [BF 07 00]
          jmp       short L_0657                     ; [EB 0D]
L_064A:   mov       di, 4                            ; [BF 04 00]
          cmp       byte ptr ds:[80h], 0             ; [80 3E 80 00 00]
          je        L_0657                           ; [74 03]
          xor       ax, ax                           ; [33 C0]
          ret                                        ; [C3]
L_0657:   push      ds                               ; [1E]
          mov       si, cs                           ; [8C CE]
          mov       ax, 89Fh                         ; [B8 9F 08]
          mov       cl, 4                            ; [B1 04]
          shr       ax, cl                           ; [D3 E8]
          add       si, ax                           ; [03 F0]
          mov       ds, si                           ; [8E DE]
          xor       ax, ax                           ; [33 C0]
          xor       si, si                           ; [33 F6]
          cmp       word ptr [si], 4F4Ch             ; [81 3C 4C 4F]
          jne       L_067E                           ; [75 0F]
          cmp       word ptr [si + 2], 4F47h         ; [81 7C 02 47 4F]
          jne       L_067E                           ; [75 08]
          push      cs                               ; [0E]
          mov       ax, 77Eh                         ; [B8 7E 07]
          push      ax                               ; [50]
          push      ds                               ; [1E]
          push      di                               ; [57]
          db 0CBh                                             ; retf 
L_067E:   pop       ds                               ; [1F]
          ret                                        ; [C3]
; -- data 0x0680..0x1308 (3209B) --
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
d_0790: db 'LOGO'
        db 0E9h, 0C6h, 00h, 33h, 0C0h, 8Eh, 0C0h, 0A0h, 19h, 00h, 26h, 0A2h, 10h, 04h, 0A0h, 18h
        db 00h, 0CDh, 10h, 0CBh, 00h, 00h, 50h, 00h, 0A0h, 05h, 0A0h, 05h, 00h, 00h, 00h, 40h
        db 00h, 0B8h, 1Fh, 0Eh, 4Dh, 69h, 63h, 72h, 6Fh, 73h, 6Fh, 66h, 74h, 20h, 57h, 69h
d_07C4: db 'ndows'
        db 00h, 21h, 0Fh, 56h, 65h, 72h, 73h, 69h, 6Fh, 6Eh, 20h, 31h, 2Eh, 30h, 33h, 00h
        db 05h, 17h, 43h, 6Fh, 70h, 79h, 72h, 69h, 67h, 68h, 74h, 20h, 28h, 63h, 29h, 20h
d_07E9: db 'Microsoft Corporation, 1985, 1986.  All Rights Reserved.'
        db 00h, 0Dh, 18h, 4Dh, 69h, 63h, 72h, 6Fh, 73h, 6Fh, 66h, 74h, 20h, 69h, 73h, 20h
d_0831: db 'a registered trademark of Microsoft Corp.'
        db 00h, 00h, 00h, 0FCh, 0E8h, 08h, 01h, 8Eh, 06h, 24h, 00h, 0E8h, 0B9h, 00h, 0E8h, 0CAh
        db 00h, 8Bh, 16h, 1Ah, 00h, 80h, 0EAh, 43h, 2Bh, 16h, 20h, 00h, 2Bh, 16h, 20h, 00h
        db 03h, 0D2h, 8Bh, 3Eh, 1Ch, 00h, 0E8h, 42h, 00h, 8Bh, 3Eh, 1Ch, 00h, 03h, 3Eh, 1Eh
        db 00h, 0A1h, 22h, 00h, 0D1h, 0E8h, 03h, 0F8h, 4Fh, 0E8h, 5Dh, 00h, 4Ah, 75h, 0E3h, 0FCh
        db 0BEh, 26h, 00h, 8Ah, 44h, 01h, 3Ch, 00h, 74h, 05h, 0E8h, 06h, 00h, 0EBh, 0F4h, 0B8h
        db 1Ah, 00h, 0CBh, 0FCh, 0ADh, 8Bh, 0D0h, 33h, 0DBh, 0B3h, 0FFh, 0B4h, 02h, 0CDh, 10h, 0ACh
        db 0Ah, 0C0h, 74h, 06h, 0B4h, 0Eh, 0CDh, 10h, 0EBh, 0F5h, 0C3h, 0FCh, 52h, 32h, 0D2h, 0BEh
        db 24h, 00h, 0D1h, 0EEh, 8Bh, 0Eh, 1Ah, 00h, 0D1h, 0E9h, 26h, 8Bh, 05h, 86h, 0C4h, 0D1h
        db 0C8h, 0D1h, 0C8h, 8Ah, 0F4h, 80h, 0E6h, 0C0h, 80h, 0E4h, 3Fh, 0Ah, 0E2h, 8Ah, 0D6h, 86h
        db 0C4h, 0ABh, 0E2h, 0E6h, 4Eh, 75h, 0DDh, 5Ah, 0C3h, 0FDh, 52h, 32h, 0D2h, 0BEh, 24h, 00h
        db 0D1h, 0EEh, 8Bh, 0Eh, 1Ah, 00h, 0D1h, 0E9h, 26h, 8Bh, 05h, 86h, 0C4h, 0D1h, 0C0h, 0D1h
        db 0C0h, 8Ah, 0F0h, 80h, 0E6h, 03h, 24h, 0FCh, 0Ah, 0C2h, 8Ah, 0D6h, 86h, 0C4h, 0ABh, 0E2h
        db 0E7h, 4Eh, 75h, 0DEh, 5Ah, 0FCh, 0C3h, 0BEh, 0Dh, 02h, 0B0h, 12h, 0F6h, 26h, 1Ah, 00h
        db 8Bh, 0F8h, 03h, 3Eh, 20h, 00h, 0BBh, 12h, 00h, 0EBh, 20h, 0B0h, 12h, 0F6h, 26h, 1Ah
        db 00h, 8Bh, 1Eh, 1Ah, 00h, 80h, 0EBh, 43h, 03h, 0C3h, 8Bh, 1Eh, 22h, 00h, 0D1h, 0EBh
        db 03h, 0C3h, 8Bh, 0F8h, 2Bh, 3Eh, 20h, 00h, 0BBh, 12h, 00h, 0A1h, 1Ah, 00h, 2Dh, 43h
        db 00h, 0B9h, 43h, 00h, 0B9h, 43h, 00h, 0F3h, 0A4h, 03h, 0F8h, 4Bh, 75h, 0F3h, 0C3h, 0B4h
        db 0Fh, 0CDh, 10h, 0A2h, 18h, 00h, 33h, 0C0h, 8Eh, 0C0h, 26h, 0A0h, 10h, 04h, 0A2h, 19h
        db 00h, 0F6h, 0D0h, 0A8h, 30h, 75h, 08h, 0F6h, 0D0h, 24h, 0EFh, 26h, 0A2h, 10h, 04h, 0B8h
        db 06h, 00h, 0CDh, 10h, 0B8h, 00h, 10h, 0B7h, 01h, 0CDh, 10h, 0B8h, 01h, 10h, 0B7h, 01h
        db 0CDh, 10h, 0C3h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 3Fh, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 3Fh, 0FFh, 0C3h
        db 0FFh, 0C0h, 00h, 00h, 00h, 0Fh, 0FFh, 0FCh, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0F0h
        db 00h, 00h, 00h, 00h, 00h, 3Fh, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 0Fh, 0FFh
        db 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 0FCh, 00h, 00h, 00h, 00h, 0FFh, 0FFh, 0FFh
        db 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 3Fh, 0FFh, 0F0h, 00h, 00h, 00h, 00h
        db 0FFh, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 03h, 0FFh
        db 0FFh, 0FFh, 0FFh, 0FCh, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 03h, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 00h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 00h
        db 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 3Fh, 0FFh, 0FCh, 00h
        db 00h, 00h, 03h, 0FFh, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 3Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
        db 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 0Fh, 0FFh, 0FFh, 0C0h, 00h, 3Fh, 0FFh
        db 0FFh, 0C0h, 00h, 3Fh, 0FFh, 0FFh, 0FFh, 0FCh, 00h, 00h, 3Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
        db 0FFh, 00h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 3Fh
        db 0FFh, 0FFh, 00h, 00h, 00h, 0Fh, 0FFh, 0FFh, 0C3h, 0FFh, 0C0h, 03h, 0FFh, 0FCh, 00h, 00h
        db 00h, 0Fh, 0FFh, 0F0h, 03h, 0FFh, 0C0h, 00h, 0Fh, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 00h, 03h, 0FFh, 0FCh, 00h
        db 00h, 00h, 0Fh, 0FFh, 0F0h, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h
        db 00h, 00h, 3Fh, 0FFh, 0FFh, 0C0h, 00h, 00h, 3Fh, 0FFh, 0FFh, 0C3h, 0FFh, 0C0h, 3Fh, 0FFh
        db 00h, 00h, 00h, 00h, 00h, 3Fh, 0FFh, 03h, 0FFh, 0C0h, 00h, 00h, 0FFh, 0FCh, 03h, 0FFh
        db 0C0h, 00h, 00h, 00h, 00h, 00h, 3Fh, 0FCh, 00h, 0FFh, 0FCh, 00h, 0Fh, 0FFh, 00h, 3Fh
        db 0FFh, 00h, 00h, 00h, 00h, 00h, 3Fh, 0FFh, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h
        db 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FFh, 0FFh, 0F0h, 00h, 00h, 0FFh, 0FFh, 0FFh, 0C3h, 0FFh
        db 0C0h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 3Fh
        db 0FCh, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0FFh, 00h, 00h
        db 00h, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0C0h, 0FFh, 0F0h, 00h, 00h
        db 00h, 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FFh, 0FFh, 0FCh, 00h, 03h, 0FFh, 0FFh
        db 0FFh, 0C3h, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0C3h, 0FFh, 0C0h
        db 00h, 00h, 0FFh, 0FCh, 3Fh, 0FCh, 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0C0h, 3Fh
        db 0FFh, 0FCh, 00h, 00h, 00h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0C0h, 0FFh
        db 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FCh, 0FFh, 0FFh, 00h
        db 0Fh, 0FFh, 0F3h, 0FFh, 0C3h, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 03h, 0FFh, 0C0h, 00h, 0Fh, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 0Fh, 0FFh, 0FFh, 0FFh, 00h, 03h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h
        db 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FCh
        db 3Fh, 0FFh, 0C0h, 3Fh, 0FFh, 0C3h, 0FFh, 0C3h, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 00h
        db 00h, 3Fh, 0FFh, 0FFh, 0F0h, 00h, 0FFh, 0FFh, 0FFh, 0F0h, 03h, 0FFh, 0C0h, 00h, 00h, 00h
        db 00h, 00h, 00h, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 0Fh, 0FFh, 00h, 00h
        db 00h, 3Fh, 0FCh, 0Fh, 0FFh, 0F0h, 0FFh, 0FFh, 03h, 0FFh, 0C3h, 0FFh, 0C3h, 0FFh, 0C0h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FCh, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0FFh, 0FFh, 03h, 0FFh, 0C0h
        db 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 0Fh
        db 0FFh, 00h, 00h, 00h, 3Fh, 0FCh, 03h, 0FFh, 0FFh, 0FFh, 0FCh, 03h, 0FFh, 0C3h, 0FFh, 0C0h
        db 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 00h
        db 3Fh, 0FCh, 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0C0h, 00h, 00h, 00h, 3Fh, 0FFh
        db 0C0h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0C0h, 0FFh, 0F0h, 00h, 00h, 00h
        db 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FCh, 00h, 0FFh, 0FFh, 0FFh, 0F0h, 03h, 0FFh
        db 0C3h, 0FFh, 0C0h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 00h
        db 3Fh, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0C0h
        db 00h, 03h, 0FFh, 0C0h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0C0h, 0FFh, 0F0h
        db 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 3Fh, 0C0h, 3Fh, 0FCh, 00h, 3Fh, 0FFh, 0FFh
        db 0C0h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 3Fh, 0FFh, 00h, 00h, 00h, 00h, 00h, 3Fh, 0FFh, 03h
        db 0FFh, 0C0h, 00h, 03h, 0FFh, 0F0h, 03h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 3Fh, 0FCh
        db 03h, 0FFh, 0F0h, 00h, 0Fh, 0FFh, 0C0h, 3Fh, 0FFh, 00h, 00h, 00h, 00h, 00h, 3Fh, 0FFh
        db 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 03h, 00h, 0Ch, 3Fh, 0FCh, 00h
        db 0Fh, 0FFh, 0FFh, 00h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 03h, 0FFh, 0FCh, 00h, 00h, 00h, 0Fh
        db 0FFh, 0F0h, 03h, 0FFh, 0C0h, 00h, 00h, 0FFh, 0FCh, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 03h, 0FFh, 0FCh, 00h, 00h, 00h
        db 0Fh, 0FFh, 0F0h, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 0Ch, 30h, 0C3h
        db 3Fh, 0FCh, 00h, 03h, 0FFh, 0FCh, 00h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 3Fh, 0FFh, 0FFh
        db 0FFh, 0FFh, 0FFh, 0FFh, 00h, 03h, 0FFh, 0C0h, 00h, 00h, 3Fh, 0FCh, 00h, 0Fh, 0FFh, 0FFh
        db 0C0h, 00h, 3Fh, 0FFh, 0FFh, 00h, 00h, 3Fh, 0FFh, 0FFh, 0FFh, 0FCh, 00h, 00h, 3Fh, 0FFh
        db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 00h, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh
        db 0Ch, 33h, 03h, 3Fh, 0FCh, 00h, 00h, 0FFh, 0F0h, 00h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 00h
        db 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 03h, 0FFh, 0C0h, 00h, 00h, 3Fh, 0FCh, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0C0h, 00h
        db 00h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h
        db 00h, 0Fh, 0FFh, 03h, 00h, 0Ch, 3Fh, 0FCh, 00h, 00h, 3Fh, 0C0h, 00h, 03h, 0FFh, 0C3h
        db 0FFh, 0C0h, 00h, 00h, 00h, 0Fh, 0FFh, 0FCh, 00h, 00h, 00h, 03h, 0FFh, 0C0h, 00h, 00h
        db 3Fh, 0FCh, 00h, 00h, 00h, 3Fh, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 0Fh, 0FFh
        db 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 0FCh, 00h, 00h, 00h, 00h, 0FFh, 0F0h, 00h
        db 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 3Fh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0FFh, 0F0h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 3Fh, 0FFh, 0C0h, 00h
        db 00h, 00h, 00h, 3Fh, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0F0h, 00h
        db 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
        db 00h, 00h, 00h, 00h, 0FFh, 0FFh, 0FFh, 00h, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0F0h
        db 00h, 00h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 3Fh
        db 0FFh, 0F0h, 00h, 00h, 00h, 00h, 0FFh, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 03h, 0FFh, 0FFh, 0FFh
        db 0FFh, 0FFh, 0F0h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FCh, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh
        db 0FFh, 0FFh, 0FFh, 0FCh, 00h, 00h, 0Fh, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 03h, 0FFh, 0FFh
        db 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh
        db 0FFh, 0F0h, 3Fh, 0FFh, 0FCh, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 0FFh
        db 0FFh, 0F0h, 00h, 03h, 0FFh, 0FFh, 0C0h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 00h, 3Fh
        db 0FFh, 0F0h, 00h, 00h, 00h, 0FFh, 0FFh, 0C0h, 00h, 3Fh, 0FFh, 0FFh, 0FFh, 0FFh, 00h, 00h
        db 0FFh, 0FFh, 0F0h, 00h, 03h, 0FFh, 0FFh, 0C0h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 0FFh, 0FFh
        db 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 3Fh, 0FFh, 0FFh, 00h, 00h, 00h, 0Fh, 0FFh, 0FFh, 0C3h, 0FFh
        db 0C0h, 0Fh, 0FFh, 0F0h, 00h, 00h, 00h, 03h, 0FFh, 0FCh, 03h, 0FFh, 0C0h, 00h, 00h, 0FFh
        db 0F0h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FCh, 00h, 0FFh, 0FFh, 0C0h, 0FFh
        db 0FFh, 0C0h, 0Fh, 0FFh, 0F0h, 00h, 00h, 00h, 03h, 0FFh, 0FCh, 00h, 0FFh, 0F0h, 00h, 00h
        db 00h, 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FFh, 0FFh, 0C0h, 00h, 00h, 3Fh, 0FFh
        db 0FFh, 0C3h, 0FFh, 0C0h, 3Fh, 0FCh, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 03h, 0FFh, 0C0h
        db 00h, 00h, 3Fh, 0FCh, 0Fh, 0FFh, 00h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 0FFh
        db 0FCh, 00h, 0Fh, 0FFh, 00h, 3Fh, 0FCh, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 0FFh
        db 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FFh, 0FFh, 0F0h, 00h
        db 00h, 0FFh, 0FFh, 0FFh, 0C3h, 0FFh, 0C0h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh
        db 0C3h, 0FFh, 0C0h, 00h, 00h, 3Fh, 0FCh, 3Fh, 0FFh, 0FFh, 0FFh, 00h, 00h, 0Fh, 0FFh, 0FFh
        db 0FFh, 0C0h, 3Fh, 0FFh, 0C0h, 00h, 00h, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 03h
        db 0FFh, 0C0h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FCh
        db 0FFh, 0FCh, 00h, 03h, 0FFh, 0F3h, 0FFh, 0C3h, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 03h, 0FFh, 0C0h, 00h, 00h, 0FFh, 0F0h, 3Fh, 0F0h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 0FFh, 0C0h, 3Fh, 0FFh, 0FFh, 0F0h, 00h, 03h, 0FFh, 0C0h, 00h, 00h, 00h
        db 00h, 00h, 00h, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 0Fh, 0FFh, 00h, 00h
        db 00h, 3Fh, 0FCh, 3Fh, 0FFh, 00h, 0Fh, 0FFh, 0C3h, 0FFh, 0C3h, 0FFh, 0C3h, 0FFh, 0C0h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0C0h, 0FFh, 0F0h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0F0h, 03h, 0FFh, 0FFh, 0FFh, 0C0h, 03h, 0FFh, 0C0h
        db 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 0Fh
        db 0FFh, 00h, 00h, 00h, 3Fh, 0FCh, 0Fh, 0FFh, 0C0h, 3Fh, 0FFh, 03h, 0FFh, 0C3h, 0FFh, 0C3h
        db 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 00h
        db 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0F0h, 00h, 0Fh, 0FFh, 0FFh, 0FCh
        db 03h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0F0h, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h
        db 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FCh, 03h, 0FFh, 0F0h, 0FFh, 0FCh, 03h, 0FFh
        db 0C3h, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh
        db 0FFh, 0FCh, 00h, 3Fh, 0F0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0C0h, 00h, 00h
        db 03h, 0FFh, 0FFh, 03h, 0FFh, 0C0h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0F0h, 0FFh, 0FFh
        db 0FFh, 0FFh, 0F0h, 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FCh, 00h, 0FFh, 0FFh, 0FFh
        db 0F0h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 03h
        db 0FFh, 0C0h, 00h, 0FFh, 0FFh, 00h, 3Fh, 0FFh, 0FFh, 0FFh, 00h, 00h, 0Fh, 0FFh, 0FFh, 0FFh
        db 0C0h, 00h, 00h, 00h, 0Fh, 0FFh, 0C0h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 03h, 0FFh
        db 0C0h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 00h, 00h, 3Fh, 0FCh, 00h
        db 3Fh, 0FFh, 0FFh, 0C0h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 3Fh, 0FCh, 00h, 00h, 00h, 00h, 00h
        db 0Fh, 0FFh, 03h, 0FFh, 0C0h, 00h, 0Fh, 0FFh, 0C0h, 0Fh, 0FFh, 00h, 00h, 00h, 00h, 00h
        db 00h, 0Fh, 0FFh, 03h, 0FFh, 0F0h, 00h, 03h, 0FFh, 0C0h, 3Fh, 0FCh, 00h, 00h, 00h, 00h
        db 00h, 0Fh, 0FFh, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 0C0h, 30h
        db 3Fh, 0FCh, 00h, 0Fh, 0FFh, 0FFh, 00h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 0Fh, 0FFh, 0F0h, 00h
        db 00h, 00h, 03h, 0FFh, 0FCh, 03h, 0FFh, 0C0h, 00h, 00h, 0FFh, 0F0h, 03h, 0FFh, 0FFh, 0FFh
        db 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FCh, 03h, 0FFh, 0FCh, 00h, 3Fh, 0FFh, 0C0h, 0Fh, 0FFh, 0F0h
        db 00h, 00h, 00h, 03h, 0FFh, 0FCh, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh
        db 0Ch, 3Fh, 03h, 3Fh, 0FCh, 00h, 03h, 0FFh, 0FCh, 00h, 03h, 0FFh, 0C3h, 0FFh, 0C0h, 00h
        db 0FFh, 0FFh, 0F0h, 00h, 03h, 0FFh, 0FFh, 0C0h, 03h, 0FFh, 0C0h, 00h, 00h, 0FFh, 0FCh, 00h
        db 3Fh, 0FFh, 0F0h, 00h, 00h, 00h, 0FFh, 0FFh, 0C0h, 00h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 00h
        db 00h, 0FFh, 0FFh, 0F0h, 00h, 03h, 0FFh, 0FFh, 0C0h, 00h, 0FFh, 0F0h, 00h, 00h, 00h, 00h
        db 00h, 0Fh, 0FFh, 0Ch, 3Fh, 03h, 3Fh, 0FCh, 00h, 00h, 0FFh, 0F0h, 00h, 03h, 0FFh, 0C3h
        db 0FFh, 0C0h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 03h, 0FFh, 0C0h, 00h, 00h
        db 3Fh, 0FCh, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0FCh, 00h, 00h, 0Fh, 0FFh, 0FFh
        db 0FFh, 0F0h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 0FFh, 0F0h, 00h
        db 00h, 00h, 00h, 00h, 0Fh, 0FFh, 0Ch, 30h, 0C3h, 3Fh, 0FCh, 00h, 00h, 3Fh, 0C0h, 00h
        db 03h, 0FFh, 0C3h, 0FFh, 0C0h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 03h, 0FFh
        db 0C0h, 00h, 00h, 3Fh, 0FCh, 00h, 00h, 0Fh, 0FFh, 0FFh, 0FFh, 0FFh, 0FFh, 00h, 00h, 00h
        db 00h, 3Fh, 0FFh, 0FFh, 00h, 00h, 00h, 00h, 03h, 0FFh, 0FFh, 0FFh, 0F0h, 00h, 00h, 00h
        db 0FFh, 0F0h, 00h, 00h, 00h, 00h, 00h, 0Fh, 0FFh, 00h, 0C0h, 30h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 0FFh, 0F0h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h

WIN_SEG1 ENDS
        END
