"""Pass 14: emit MASM-style header files (windows.inc, kernel.inc, gdi.inc, user.inc).

These files are NOT included by the seg*.asm sources (the sources are already
byte-exact via raw bytes). They serve as:

  1. Documentation: anyone reading the project can browse all known APIs and
     constants in one place, in standard MASM .inc format.

  2. Future use: when individual functions are lifted to a more semantic form
     (e.g., editing `mov ax, [bp+10]` to `mov ax, [bp.flags]`), these
     definitions provide the symbol space.

  3. Reference for clean-room reimplementation: anyone attempting to
     reimplement Windows 1.x from scratch can use these definitions as the
     boundary of compatibility.

Output files (created in inc/ at repo root):
  inc/windows.inc    - common types, message constants, ROP codes, VK_*
  inc/kernel.inc     - KERNEL.EXE export prototypes
  inc/user.inc       - USER.EXE export prototypes
  inc/gdi.inc        - GDI.EXE export prototypes
  inc/cmacros.inc    - common prologue/epilogue / call convention macros

This pass writes new files only; does NOT modify src/.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from state import REPO, log  # noqa: E402
from win1x_api_signatures import SIGNATURES, type_size  # noqa: E402
from win1x_constants import WIN1X_CONSTANTS, TOP_SAFE  # noqa: E402

PASS_NAME = "pass14_emit_headers"
INC_DIR = REPO / "inc"


HEADER_BANNER = """; ======================================================================
; {filename}
; Reconstructed Win 1.x SDK header (research/educational reference)
; ======================================================================
; Generated by `bootstrap/analyze/pass14_emit_headers.py`.
;
; These declarations are reconstructed from:
;   - Charles Petzold, *Programming Windows*, Microsoft Press, 1988.
;   - Public NE export tables of the Windows 1.03 binaries.
;   - Microsoft Win 1.0 SDK reference (cited as public reference material).
;
; They are best-effort reconstructions and may contain errors. They are
; provided so anyone studying the Windows 1.x source tree has a familiar
; symbol space, in standard MASM .inc format.
;
; Type sizes (16-bit Windows 1.x):
;   BYTE   = 1     WORD  = 2    DWORD = 4
;   BOOL   = 2     HANDLE= 2    HWND  = 2     HDC = 2
;   LPSTR  = 4     LPVOID= 4    FARPROC = 4
;   WPARAM = 2     LPARAM= 4    LRESULT = 4
; ======================================================================

"""


def emit_windows_inc() -> str:
    """Top-level windows.inc with types, common constants."""
    out: list[str] = [HEADER_BANNER.format(filename="windows.inc")]

    # ------------- Type aliases --------------------------------------------
    out.append("; ---- Type aliases (informational; MASM is untyped) ----\n")
    out.append("BYTE_T      EQU 1\n")
    out.append("WORD_T      EQU 2\n")
    out.append("DWORD_T     EQU 4\n")
    out.append("\n")

    # ------------- Messages WM_* -------------------------------------------
    out.append("; ---- Window messages (WM_*) ----\n")
    wm_entries = sorted(
        (v, n) for v, n in WIN1X_CONSTANTS.items()
        if isinstance(n, str) and n.startswith("WM_") and "|" not in n
    )
    for v, name in wm_entries:
        out.append(f"{name:<24s} EQU {v:#06X}\n")
    out.append("\n")

    # ------------- VK_* keys -----------------------------------------------
    out.append("; ---- Virtual key codes (VK_*) ----\n")
    vk_entries = sorted(
        (v, n) for v, n in WIN1X_CONSTANTS.items()
        if isinstance(n, str) and n.startswith("VK_")
    )
    for v, name in vk_entries:
        out.append(f"{name:<24s} EQU {v:#06X}\n")
    out.append("\n")

    # ------------- GMEM_* / LMEM_* -----------------------------------------
    out.append("; ---- Global memory flags (GMEM_*) ----\n")
    out.append("GMEM_FIXED              EQU 0000h\n")
    out.append("GMEM_MOVEABLE           EQU 0002h\n")
    out.append("GMEM_NOCOMPACT          EQU 0020h\n")
    out.append("GMEM_NODISCARD          EQU 0040h\n")
    out.append("GMEM_ZEROINIT           EQU 0080h\n")
    out.append("GMEM_NOT_BANKED         EQU 0100h\n")
    out.append("GMEM_SHARE              EQU 0200h\n")
    out.append("GMEM_DDESHARE           EQU 0200h\n")
    out.append("GMEM_NOTIFY             EQU 0400h\n")
    out.append("GMEM_DISCARDABLE        EQU 0F00h\n")
    out.append("\n")
    out.append("; ---- Local memory flags (LMEM_*) ----\n")
    out.append("LMEM_FIXED              EQU 0000h\n")
    out.append("LMEM_MOVEABLE           EQU 0002h\n")
    out.append("LMEM_NOCOMPACT          EQU 0010h\n")
    out.append("LMEM_NODISCARD          EQU 0020h\n")
    out.append("LMEM_ZEROINIT           EQU 0040h\n")
    out.append("LMEM_DISCARDABLE        EQU 0F00h\n")
    out.append("\n")

    # ------------- Window styles WS_* --------------------------------------
    out.append("; ---- Window styles (WS_*) ----\n")
    out.append("WS_OVERLAPPED           EQU 00000000h\n")
    out.append("WS_POPUP                EQU 80000000h\n")
    out.append("WS_CHILD                EQU 40000000h\n")
    out.append("WS_MINIMIZE             EQU 20000000h\n")
    out.append("WS_VISIBLE              EQU 10000000h\n")
    out.append("WS_DISABLED             EQU 08000000h\n")
    out.append("WS_CLIPSIBLINGS         EQU 04000000h\n")
    out.append("WS_CLIPCHILDREN         EQU 02000000h\n")
    out.append("WS_MAXIMIZE             EQU 01000000h\n")
    out.append("WS_CAPTION              EQU 00C00000h\n")
    out.append("WS_BORDER               EQU 00800000h\n")
    out.append("WS_DLGFRAME             EQU 00400000h\n")
    out.append("WS_VSCROLL              EQU 00200000h\n")
    out.append("WS_HSCROLL              EQU 00100000h\n")
    out.append("WS_SYSMENU              EQU 00080000h\n")
    out.append("WS_THICKFRAME           EQU 00040000h\n")
    out.append("WS_GROUP                EQU 00020000h\n")
    out.append("WS_TABSTOP              EQU 00010000h\n")
    out.append("\n")

    # ------------- SW_* (ShowWindow) ---------------------------------------
    out.append("; ---- ShowWindow nCmdShow (SW_*) ----\n")
    out.append("SW_HIDE                 EQU 0\n")
    out.append("SW_SHOWNORMAL           EQU 1\n")
    out.append("SW_SHOWMINIMIZED        EQU 2\n")
    out.append("SW_SHOWMAXIMIZED        EQU 3\n")
    out.append("SW_SHOWNOACTIVATE       EQU 4\n")
    out.append("SW_SHOW                 EQU 5\n")
    out.append("SW_MINIMIZE             EQU 6\n")
    out.append("SW_SHOWMINNOACTIVE      EQU 7\n")
    out.append("SW_SHOWNA               EQU 8\n")
    out.append("SW_RESTORE              EQU 9\n")
    out.append("\n")

    # ------------- Raster ops (ROP codes for BitBlt) -----------------------
    out.append("; ---- Raster operation codes (BitBlt) ----\n")
    rops = [
        (0x00CC0020, "SRCCOPY"),
        (0x00EE0086, "SRCPAINT"),
        (0x008800C6, "SRCAND"),
        (0x00660046, "SRCINVERT"),
        (0x00440328, "SRCERASE"),
        (0x00330008, "NOTSRCCOPY"),
        (0x001100A6, "NOTSRCERASE"),
        (0x00C000CA, "MERGECOPY"),
        (0x00BB0226, "MERGEPAINT"),
        (0x00F00021, "PATCOPY"),
        (0x00FB0A09, "PATPAINT"),
        (0x005A0049, "PATINVERT"),
        (0x00550009, "DSTINVERT"),
        (0x00000042, "BLACKNESS"),
        (0x00FF0062, "WHITENESS"),
    ]
    for v, name in rops:
        out.append(f"{name:<24s} EQU {v:08X}h\n")
    out.append("\n")

    # ------------- MessageBox styles ---------------------------------------
    out.append("; ---- MessageBox styles (MB_*) ----\n")
    out.append("MB_OK                   EQU 0000h\n")
    out.append("MB_OKCANCEL             EQU 0001h\n")
    out.append("MB_ABORTRETRYIGNORE     EQU 0002h\n")
    out.append("MB_YESNOCANCEL          EQU 0003h\n")
    out.append("MB_YESNO                EQU 0004h\n")
    out.append("MB_RETRYCANCEL          EQU 0005h\n")
    out.append("MB_ICONHAND             EQU 0010h\n")
    out.append("MB_ICONQUESTION         EQU 0020h\n")
    out.append("MB_ICONEXCLAMATION      EQU 0030h\n")
    out.append("MB_ICONASTERISK         EQU 0040h\n")

    return "".join(out)


def emit_module_inc(module_name: str) -> str:
    """Emit an .inc file for one module (KERNEL, USER, or GDI)."""
    out: list[str] = [HEADER_BANNER.format(filename=f"{module_name.lower()}.inc")]
    out.append(f"; ---- Imported procedure prototypes (from {module_name}.EXE) ----\n")
    out.append(";\n")
    out.append("; Reference notation (informational comments only).\n")
    out.append(";\n\n")

    # Group APIs of this module
    apis = sorted(name for name, sig in SIGNATURES.items()
                  if sig.get("module") == module_name)
    for api in apis:
        sig = SIGNATURES[api]
        params = sig.get("params", [])
        ret = sig.get("return", "?")
        if params:
            param_str = ", ".join(f"{p['type']} {p['name']}" for p in params)
        else:
            param_str = "void"
        total = sig.get("params_total_size", 0)
        ordinal = sig.get("ordinal")
        ord_str = f"  @{ordinal}" if ordinal is not None else ""
        out.append(f"; {api}({param_str}) -> {ret}\n")
        out.append(f";   args: {total}B   pascal far{ord_str}\n")
        # Equivalent EXTRN line (commented because not actually included)
        out.append(f";   EXTRN {api}:FAR\n")
        out.append("\n")
    return "".join(out)


def emit_cmacros_inc() -> str:
    """Common prologue/epilogue macros (a la cmacros.inc that MS shipped)."""
    out: list[str] = [HEADER_BANNER.format(filename="cmacros.inc")]
    out.append("""\
; ---- Standard FAR PASCAL prologue ----
; Usage:
;   MyProc PROC FAR
;       cProc 4               ; reserve 4 bytes for locals
;       parmW hWnd            ; declare a WORD parameter named hWnd
;       parmD lpsz            ; declare a DWORD parameter
;       cBegin
;       ...
;       cEnd
;   MyProc ENDP

; These macros are FOR REFERENCE; the seg*.asm sources do not currently use
; them (they use raw byte directives). Listed here so anyone porting work
; toward MASM-style sources has the macro vocabulary.

cProc       MACRO   locals
    push    bp
    mov     bp, sp
    IF locals
    sub     sp, locals
    ENDIF
    ENDM

cBegin      MACRO
    ENDM

cEnd        MACRO   ret_size
    IF ret_size
    mov     sp, bp
    pop     bp
    retf    ret_size
    ELSE
    mov     sp, bp
    pop     bp
    retf
    ENDIF
    ENDM

parmW       MACRO   name
    name    EQU [bp+6]
    ENDM

parmD       MACRO   name
    name    EQU [bp+6]
    ENDM

localW      MACRO   name, ofs
    name    EQU [bp-ofs]
    ENDM
""")
    return "".join(out)


def main() -> int:
    INC_DIR.mkdir(parents=True, exist_ok=True)
    log(PASS_NAME, f"emitting MASM-style headers to {INC_DIR}")

    files_written: list[str] = []

    # windows.inc
    p = INC_DIR / "windows.inc"
    p.write_text(emit_windows_inc(), encoding="utf-8", newline="\n")
    files_written.append(str(p))
    log(PASS_NAME, f"  wrote {p.name} ({p.stat().st_size} bytes)")

    # per-module .inc
    for mod in ("KERNEL", "USER", "GDI"):
        p = INC_DIR / f"{mod.lower()}.inc"
        p.write_text(emit_module_inc(mod), encoding="utf-8", newline="\n")
        files_written.append(str(p))
        log(PASS_NAME, f"  wrote {p.name} ({p.stat().st_size} bytes)")

    # cmacros.inc
    p = INC_DIR / "cmacros.inc"
    p.write_text(emit_cmacros_inc(), encoding="utf-8", newline="\n")
    files_written.append(str(p))
    log(PASS_NAME, f"  wrote {p.name} ({p.stat().st_size} bytes)")

    # readme.md for inc dir
    readme = INC_DIR / "README.md"
    readme.write_text(f"""# inc/ — Reconstructed Win 1.x headers

This directory contains MASM-style `.inc` reference files reconstructed from
the public Windows 1.0 SDK reference, Petzold's *Programming Windows* (1988),
and the NE export tables.

These files are **not currently included** by the seg*.asm sources (those
sources are byte-exact via raw `db` directives). They serve as:

1. Documentation — browse all known APIs and constants in one place.
2. Future scaffolding — when individual functions are progressively lifted
   to a more semantic form, these declarations provide the symbol space.
3. Clean-room reference — anyone attempting a clean-room reimplementation
   can use these as the public-API boundary they must respect.

## Files

| File         | Contents                                          |
|--------------|---------------------------------------------------|
| windows.inc  | Common types, WM_* messages, VK_* keys, GMEM_*,   |
|              | LMEM_*, WS_*, SW_*, ROP codes, MB_* styles        |
| kernel.inc   | KERNEL.EXE exported procedure prototypes          |
| user.inc     | USER.EXE exported procedure prototypes            |
| gdi.inc      | GDI.EXE exported procedure prototypes             |
| cmacros.inc  | Standard FAR PASCAL prologue/epilogue macros      |

Generated by `bootstrap/analyze/pass14_emit_headers.py`.
""", encoding="utf-8", newline="\n")
    files_written.append(str(readme))
    log(PASS_NAME, f"  wrote {readme.name}")

    log(PASS_NAME, f"DONE: {len(files_written)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
