"""Pass 24: Batch byte-exact verification with iterative refinement.

For each mini-stub candidate from pass23:
  1. Generate a .asm with the disassembled instructions (capstone-style)
     after applying a long list of pretty-printer -> MASM 4.0 fixups.
  2. Assemble with MASM 4.0 inside DOSBox-X (one spawn for the whole batch).
  3. Read the produced .OBJ, locate the function's bytes inside, compare
     against the original bytes.
  4. ITERATIVE REFINEMENT: for any function whose generated bytes diverge
     from the original (encoding ambiguities like `xchg ch, cl` 86 CD vs
     86 E9), parse the .LST file to identify the offending instruction(s)
     and replace them with raw `db` directives carrying the ORIGINAL
     bytes. Re-assemble and re-check. This iterates up to N rounds or
     until no further progress is made.

The end goal: every recoverable function ends up as a .asm that MASM 4.0
compiles to byte-exact original output, possibly with some instructions
emitted as `db` sequences when MASM's preferred encoding differs.

Artifacts:
  tools/dos/work/batch/<MOD>_<NAME>.asm  - per-function source (final form)
  tools/dos/work/batch/<MOD>_<NAME>.obj  - assembled by MASM
  tools/dos/work/batch/<MOD>_<NAME>.lst  - assembler listing (offsets+bytes)
  state/analyze/pass24/results.json      - per-function status, every round
  state/analyze/pass24/summary.md        - human-readable report
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PASS23 = REPO / 'state' / 'analyze' / 'pass23'
PASS24 = REPO / 'state' / 'analyze' / 'pass24'
WORK = REPO / 'tools' / 'dos' / 'work' / 'batch'

MAX_REFINEMENT_ROUNDS = 3


# --------------------------------------------------------------------------
# .asm pretty-printer cleanup
# --------------------------------------------------------------------------

def clean_asm_line(line):
    out = re.sub(r';.*$', '', line).rstrip()
    return out.lstrip()


def rewrite_for_masm(line):
    """Convert capstone-style disasm into MASM 4.0-friendly syntax."""
    def hex_fix(m):
        v = m.group(1)
        if v.lower().endswith('h'):
            return v
        if v.lower().startswith('0x'):
            v = v[2:]
            if v and v[0].isalpha():
                v = '0' + v
            return v + 'h'
        return v
    line = re.sub(r'\b(0x[0-9a-fA-F]+)\b', hex_fix, line)
    # 'retf' -> 'ret' (MASM auto-picks CB/CA based on PROC FAR)
    line = re.sub(r'\bretf\b', 'ret', line)
    # 'ljmp' / 'lcall' -> 'jmp dword ptr' / 'call dword ptr'
    line = re.sub(r'\bljmp\b', 'jmp dword ptr', line)
    line = re.sub(r'\blcall\b', 'call dword ptr', line)
    # 'mov sreg, [imm]' -> 'mov sreg, ds:[imm]'
    line = re.sub(
        r'(\bmov\s+(?:[ecds]s)\s*,\s*)(?:word\s+ptr\s+)?(\[)',
        r'\1ds:\2', line, flags=re.I)
    # 'les di, ptr ss:[bx+4]' -> 'les di, ss:[bx+4]'
    line = re.sub(r'(\b(?:les|lds|lfs|lgs|lss)\s+\w+\s*,\s*)ptr\s+',
                   r'\1', line, flags=re.I)
    # String instructions: drop operand list -- MASM 4.0 wants implicit form
    line = re.sub(
        r'\b(rep|repe|repz|repne|repnz)?\s*'
        r'(scasb|scasw|movsb|movsw|stosb|stosw|lodsb|lodsw|cmpsb|cmpsw|insb|insw|outsb|outsw)\b'
        r'.*$',
        lambda m: f"{m.group(1) or ''} {m.group(2)}".strip(),
        line, flags=re.I)
    # Capstone in 16-bit mode mislabels 99h -> 'cdq'; in 16-bit it's 'cwd'
    line = re.sub(r'\bcdq\b', 'cwd', line, flags=re.I)
    line = re.sub(r'\bcwde\b', 'cbw', line, flags=re.I)
    # 'pop word ptr cs:[X]' -> 'pop cs:[X]'
    line = re.sub(r'(\bpop\s+)word\s+ptr\s+', r'\1', line, flags=re.I)
    # 'push word ptr cs:[X]' -> 'push cs:[X]'
    line = re.sub(r'(\bpush\s+)word\s+ptr\s+(?=[ecds]s:)',
                   r'\1', line, flags=re.I)
    # Capstone sometimes writes 'jmpf' for far jumps; MASM wants 'jmp far ptr'
    line = re.sub(r'\bjmpf\b', 'jmp far ptr', line, flags=re.I)
    line = re.sub(r'\bcallf\b', 'call far ptr', line, flags=re.I)
    # Force memory operand parsing for bracketed absolute addresses.
    # `cmp al, byte ptr [04h]` gets parsed by MASM 4.0 as `cmp al, 4`
    # (immediate, because `[X]` with an integer is treated as a parenthesised
    # expression). The cure is an explicit segment override: `ds:[04h]`.
    # Apply only when there is no segment override already.
    line = re.sub(
        r'(?<![a-zA-Z][a-zA-Z]:)\[([0-9][0-9A-Fa-fxXhH]*)\]',
        r'ds:[\1]', line)
    return line


# --------------------------------------------------------------------------
# Dangling label patching (jumps/calls to L_xxxx not in our segment)
# --------------------------------------------------------------------------

def hex_lit(byte_v):
    s = f'{byte_v:02X}'
    return ('0' + s if s[0] in 'ABCDEF' else s) + 'h'


def db_directive(raw_bytes, comment=''):
    args = ', '.join(hex_lit(b) for b in raw_bytes)
    return f"        db    {args}    ; {comment}".rstrip()


def patch_dangling_labels(asm_lines, byte_seq):
    """Replace `j* L_xxxx` / `call L_xxxx` references with raw `db` bytes,
    matched in instruction order via a Capstone disassembly of byte_seq."""
    import capstone
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_16)
    md.detail = False

    branch_bytes = []
    for ins in md.disasm(byte_seq, 0):
        if ins.mnemonic.startswith('j') or ins.mnemonic in (
                'call', 'loop', 'loope', 'loopne', 'loopz', 'loopnz'):
            op_str = ins.op_str.strip()
            if op_str.startswith('0x') or op_str.startswith('-'):
                branch_bytes.append(bytes(ins.bytes))

    out = []
    bidx = 0
    # A "dangling branch" line is any j*/jmp/call/loop whose target is either:
    #   - a label name (L_xxxx) we don't define, or
    #   - a numeric literal (e.g. `call 0`, `jmp 1234h`) that points outside
    #     our synthetic single-function segment.
    # In all such cases we replace the source with a raw db opcode sequence.
    branch_re = re.compile(
        r'^\s*(j\w+|jmp|call|loop\w*)\s+'
        r'(?:L_[0-9A-Fa-f]+|[-+]?[0-9][0-9A-Fa-fxXhH]*)'
        r'\s*$', re.I)
    for line in asm_lines:
        m = branch_re.match(line)
        if m and bidx < len(branch_bytes):
            raw = branch_bytes[bidx]
            mnem = m.group(1).lower()
            line = db_directive(raw, f"was {mnem} (raw bytes)")
            bidx += 1
        out.append(line)
    return out


# --------------------------------------------------------------------------
# Function source assembly
# --------------------------------------------------------------------------

def make_asm_source(name, asm_lines, byte_seq, has_frame=False):
    """Wrap a function body in a minimal MASM source unit.

    If `has_frame` is True we add a near-dummy DGROUP/DATA segment so the
    cMacros prologue references work; for now we just emit the same skeleton.
    """
    cleaned = []
    for ln in asm_lines:
        c = clean_asm_line(ln)
        c = rewrite_for_masm(c)
        if c:
            cleaned.append(c)
    cleaned = patch_dangling_labels(cleaned, byte_seq)
    body = '\n'.join('        ' + ln.lstrip() if not ln.lstrip().startswith('db ')
                    else ln for ln in cleaned)
    return f"""\
; Auto-generated for byte-exact verification (pass24).
; Original function: {name}

        .186                     ; enable 80186/80286 immediate-shift opcodes

_TEXT   SEGMENT BYTE PUBLIC 'CODE'
        ASSUME  CS:_TEXT

PUBLIC  {name}

{name} PROC FAR
{body}
{name} ENDP

_TEXT   ENDS
        END
"""


# --------------------------------------------------------------------------
# .LST parsing
# --------------------------------------------------------------------------

LST_INSTR_RE = re.compile(
    r'^\s*([0-9A-Fa-f]{4})\s+'                       # offset
    # 1+ hex tokens, separated by EITHER ":" (with optional single space) or
    # exactly one space. This is tight enough to prevent greedy matching from
    # eating instruction mnemonics that happen to be valid hex words (e.g.
    # `dec`, `add`, `cbf`, etc.) which sit after the wider source-column gap.
    r'([0-9A-Fa-f]{2,8}(?:(?::[ ]?| )[0-9A-Fa-f]{2,8})*)'
    r'\s{2,}'                                         # wide gap (>=2 spaces)
    r'([A-Za-z][^\r\n]*?)$'                           # source (starts with letter)
)


def _lst_token_to_bytes(token):
    """Convert a single LST hex token to actual on-disk bytes.

    MASM 4.0 displays:
      - 8-bit immediates and bytes as 2 hex digits (e.g. `8B`)        -> 1 byte
      - 16-bit immediates / operands as 4 hex digits (e.g. `0002`)     -> 2 bytes LE
      - 32-bit immediates as 8 hex digits (rare)                        -> 4 bytes LE
    """
    n = len(token)
    val = int(token, 16)
    if n == 2:
        return bytes([val])
    if n == 4:
        return bytes([val & 0xff, (val >> 8) & 0xff])
    if n == 8:
        return bytes([val & 0xff, (val >> 8) & 0xff,
                       (val >> 16) & 0xff, (val >> 24) & 0xff])
    # Fallback: parse as raw hex
    if n % 2 == 0:
        return bytes.fromhex(token)
    return b''


def parse_lst_instructions(lst_path, func_name):
    """Parse a MASM 4.0 listing and return a list of dicts:
        { 'offset': int, 'bytes': bytes, 'source': str }
    for every instruction inside the named PROC FAR ... ENDP block.
    """
    if not lst_path.exists():
        return []
    text = lst_path.read_text(encoding='ascii', errors='ignore')
    out = []
    in_proc = False
    proc_start_offset = None
    for line in text.splitlines():
        if re.search(rf'\b{re.escape(func_name)}\s+PROC\s+FAR\b', line):
            in_proc = True
            continue
        if re.search(rf'\b{re.escape(func_name)}\s+ENDP\b', line):
            break
        if not in_proc:
            continue
        m = LST_INSTR_RE.match(line)
        if not m:
            continue
        offset = int(m.group(1), 16)
        if proc_start_offset is None:
            proc_start_offset = offset
        byte_str = m.group(2).replace(':', ' ')
        byte_tokens = byte_str.split()
        try:
            raw = b''.join(_lst_token_to_bytes(t) for t in byte_tokens)
        except ValueError:
            continue
        out.append({
            'offset': offset - proc_start_offset,
            'bytes': raw,
            'source': m.group(3).strip(),
        })
    return out


# --------------------------------------------------------------------------
# Refinement: replace diverging instructions with `db` raw bytes
# --------------------------------------------------------------------------

def rebuild_body_from_lst(lst_records, expected_bytes):
    """Rebuild the function body using the .LST records as the source of
    truth. For each instruction whose generated bytes match expected at the
    same offset, emit its original source text. For each mismatch, emit a
    `db` directive carrying the ORIGINAL bytes.

    Returns (new_body_lines, n_refinements) or (None, 0) if the .LST records
    don't cover the whole expected byte range (in which case we can't safely
    rebuild without risking truncation).
    """
    if not lst_records:
        return None, 0

    # Verify .LST bytes cover the full expected range exactly.
    total_generated = sum(len(r['bytes']) for r in lst_records)
    if total_generated != len(expected_bytes):
        # The .LST didn't produce bytes 1:1 with the original (length diff).
        # We can't safely rebuild because the instruction lengths differ.
        return None, 0

    out = []
    n_changed = 0
    for rec in lst_records:
        off = rec['offset']
        gen = rec['bytes']
        expected_chunk = expected_bytes[off:off + len(gen)]
        if gen == expected_chunk:
            # Keep the original source line. It assembled correctly.
            # Note: `source` from .LST has trimmed whitespace; preserve a
            # standard indent.
            src = rec['source']
            out.append('        ' + src)
        else:
            n_changed += 1
            out.append(db_directive(
                expected_chunk,
                f"was '{rec['source']}' (MASM encoding differed)"))
    return out, n_changed


# --------------------------------------------------------------------------
# OBJ inspection
# --------------------------------------------------------------------------

def find_func_bytes_in_obj(obj_path, expected_bytes):
    if not obj_path.exists():
        return None, 'no obj produced'
    data = obj_path.read_bytes()
    idx = data.find(expected_bytes)
    if idx >= 0:
        return data[idx:idx + len(expected_bytes)], f'found at OBJ offset 0x{idx:x}'
    for prefix_len in range(len(expected_bytes) - 1, 0, -1):
        idx = data.find(expected_bytes[:prefix_len])
        if idx >= 0:
            actual = data[idx:idx + len(expected_bytes)]
            return actual, (f'partial match: first {prefix_len} bytes ok at '
                            f'OBJ offset 0x{idx:x}, then divergence')
    return None, 'no recognizable prefix in OBJ'


# --------------------------------------------------------------------------
# Batch driver
# --------------------------------------------------------------------------

def stage_asm_files(candidates):
    """Generate the per-candidate .ASM files. Returns a list of dicts with
    metadata ready for batch assembly. Filenames are kept to 8 chars max
    (MASM 4.0 8.3 limitation)."""
    out = []
    short_used = set()
    for c in candidates:
        unique = f"{c['module']}_{c['name']}"
        short = unique[:8].upper()
        base = short
        n = 0
        while base in short_used:
            n += 1
            # When N is 1..9 we have 7+1=8 chars; for n>=10 we have to drop
            # another char of the prefix so the total stays at 8.
            digits = str(n)
            base = (short[:8 - len(digits)] + digits)
        short_used.add(base)
        asm_path = WORK / f'{base}.ASM'
        byte_seq = bytes.fromhex(c['body_bytes_hex'])
        src = make_asm_source(c['name'], c['asm_lines'], byte_seq,
                                has_frame=c.get('has_frame', False))
        asm_path.write_text(src, encoding='ascii')
        out.append({**c, 'short': base, 'asm_path': asm_path,
                    'byte_seq': byte_seq})
    return out


def write_build_bat(asm_files):
    bat = ['echo === pass24 batch === > out.txt']
    for a in asm_files:
        bat.append(f"echo --- {a['short']} ({a['module']}::{a['name']}) --- >> out.txt")
        bat.append(f"masm {a['short']},{a['short']},{a['short']},nul; > {a['short']}.LOG")
        bat.append(f"type {a['short']}.LOG >> out.txt")
    bat.append('echo === DONE === >> out.txt')
    (WORK / 'build.bat').write_text('\n'.join(bat) + '\n', encoding='ascii')


def run_masm_batch():
    dosbuild = REPO / 'tools' / 'dos' / 'dosbuild.sh'
    cmd = ['wsl', '--', 'bash', str(dosbuild).replace('\\', '/').replace(
        'C:', '/mnt/c'), str(WORK).replace('\\', '/').replace('C:', '/mnt/c'),
        'build.bat']
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    return r


def inspect_round(asm_files):
    """For each file, check whether its OBJ contains the expected bytes.
    Returns a list of dicts."""
    results = []
    for a in asm_files:
        obj = WORK / f"{a['short']}.OBJ"
        lst = WORK / f"{a['short']}.LST"
        expected = a['byte_seq']
        actual, note = find_func_bytes_in_obj(obj, expected)
        match = (actual == expected)
        results.append({
            **{k: a[k] for k in ('module', 'name', 'short',
                                   'instruction_count')},
            'expected_hex': expected.hex().upper(),
            'actual_hex': actual.hex().upper() if actual else '',
            'match': match,
            'note': note,
            'lst_path': str(lst),
            'asm_path': str(a['asm_path']),
        })
    return results


def refine_candidates(asm_files, results):
    """For every non-matching candidate that produced an OBJ + LST, REBUILD
    its .asm body from the .LST itself - keeping each instruction's source
    text when it assembled correctly, and replacing it with a `db` directive
    when MASM picked a different encoding. Returns the list of files that
    were actually refined."""
    refined = []
    for a, r in zip(asm_files, results):
        if r['match']:
            continue
        lst = Path(r['lst_path'])
        if not lst.exists():
            continue
        records = parse_lst_instructions(lst, a['name'])
        if not records:
            continue
        new_body, n_changed = rebuild_body_from_lst(records, a['byte_seq'])
        if new_body is None or n_changed == 0:
            continue
        # Rewrite the .asm with the new body
        current = a['asm_path'].read_text(encoding='ascii').splitlines()
        proc_start, proc_end = None, None
        for i, ln in enumerate(current):
            if re.search(rf"\b{re.escape(a['name'])}\s+PROC\s+FAR", ln):
                proc_start = i + 1
            elif proc_start is not None and re.search(
                    rf"\b{re.escape(a['name'])}\s+ENDP", ln):
                proc_end = i
                break
        if proc_start is None or proc_end is None:
            continue
        new_full = current[:proc_start] + new_body + current[proc_end:]
        a['asm_path'].write_text('\n'.join(new_full) + '\n', encoding='ascii')
        refined.append((a['short'], n_changed))
    return refined


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    PASS24.mkdir(parents=True, exist_ok=True)
    WORK.mkdir(parents=True, exist_ok=True)

    # Clean previous work
    for f in WORK.glob('*'):
        if f.is_file():
            f.unlink()

    # Load all candidates - skip ones where pass23 couldn't confirm the
    # disassembled bytes against the original segment bytes (those have
    # disasm ambiguity and would taint our byte-exact claim).
    all_candidates = []
    dropped = 0
    for jp in sorted(PASS23.glob('*.json')):
        d = json.loads(jp.read_text(encoding='utf-8'))
        for c in d['candidates']:
            if not c.get('matches_seg', False):
                dropped += 1
                continue
            c['module'] = d['module']
            all_candidates.append(c)
    print(f'Loaded {len(all_candidates)} candidates from pass23 '
          f'({dropped} dropped - disasm bytes did not match segment).\n')

    # Stage MASM toolchain
    combined = REPO / 'tools' / 'dos' / 'combined'
    for tool in ['MASM.EXE']:
        dest = WORK / tool
        if not dest.exists():
            shutil.copy2(combined / tool, dest)

    # Generate initial .asm files
    asm_files = stage_asm_files(all_candidates)

    history = []  # per-round results

    for round_idx in range(MAX_REFINEMENT_ROUNDS):
        print(f'\n=== Round {round_idx + 1} ===')
        write_build_bat(asm_files)
        r = run_masm_batch()
        print(f'  DOSBox-X exit code: {r.returncode}')
        results = inspect_round(asm_files)
        matched = sum(1 for x in results if x['match'])
        print(f'  {matched}/{len(results)} byte-exact matches')
        history.append({'round': round_idx + 1, 'matched': matched,
                         'total': len(results)})
        if matched == len(results):
            print('  ALL candidates matched - stopping early.')
            break
        if round_idx + 1 < MAX_REFINEMENT_ROUNDS:
            refined = refine_candidates(asm_files, results)
            print(f'  Refined {len(refined)} candidates for next round.')
            if not refined:
                print('  No further refinement possible - stopping.')
                break

    # Save final results
    final_results = inspect_round(asm_files)
    (PASS24 / 'results.json').write_text(json.dumps(final_results, indent=2),
                                          encoding='utf-8')
    (PASS24 / 'history.json').write_text(json.dumps(history, indent=2),
                                          encoding='utf-8')

    # Print final summary
    matched = sum(1 for r in final_results if r['match'])
    print(f'\n===== FINAL RESULTS =====')
    print(f'  {matched}/{len(final_results)} byte-exact matches')
    print(f'  Refinement history: {history}')
    print()
    print(f"{'Module':<10}{'Name':<25}{'Status':<10}{'Note'}")
    print('-' * 90)
    for r in final_results:
        status = 'MATCH' if r['match'] else 'FAIL'
        print(f"{r['module']:<10}{r['name']:<25}{status:<10}{r['note']}")

    # Markdown report
    md = ['# Pass 24: Byte-exact verification batch\n']
    md.append(f'Verified **{matched}/{len(final_results)}** mini-stub '
              f'functions byte-exact against original binaries using MASM '
              f'4.0 + DOSBox-X.\n')
    md.append('Refinement rounds: ' + ' → '.join(
        f"{h['matched']}/{h['total']}" for h in history) + '\n')
    md.append('| Module | Function | Match | Bytes | Note |')
    md.append('|---|---|---|---|---|')
    for r in final_results:
        ok = 'YES' if r['match'] else 'no'
        md.append(f"| `{r['module']}` | `{r['name']}` | {ok} | "
                  f"`{r['expected_hex']}` | {r['note']} |")
    (PASS24 / 'summary.md').write_text('\n'.join(md), encoding='utf-8')


if __name__ == '__main__':
    main()
