"""Pass 24: Batch byte-exact verification with iterative refinement.

For each mini-stub candidate from pass23:
  1. Generate a .asm with the disassembled instructions (capstone-style)
     after applying a long list of pretty-printer -> MASM 4.0 fixups.
  2. Assemble with MASM 4.0 inside DOSBox-X (one spawn for the whole batch).
  3. Read the produced .OBJ, locate the function's bytes inside, compare
     against the original bytes.
  4. ITERATIVE REFINEMENT: for any function whose generated bytes diverge
     from the original (encoding ambiguities like `xchg ch, cl` 86 CD vs
     86 E9), parse the .LST file to identify the offending instruction(s)
     and replace them with raw `db` directives carrying the ORIGINAL
     bytes. Re-assemble and re-check. This iterates up to N rounds or
     until no further progress is made.

The end goal: every recoverable function ends up as a .asm that MASM 4.0
compiles to byte-exact original output, possibly with some instructions
emitted as `db` sequences when MASM's preferred encoding differs.

Artifacts:
  tools/dos/work/batch/<MOD>_<NAME>.asm  - per-function source (final form)
  tools/dos/work/batch/<MOD>_<NAME>.obj  - assembled by MASM
  tools/dos/work/batch/<MOD>_<NAME>.lst  - assembler listing (offsets+bytes)
  state/analyze/pass24/results.json      - per-function status, every round
  state/analyze/pass24/summary.md        - human-readable report
"""
import hashlib
import json
import os
import re
import shutil
import subprocess
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PASS23 = REPO / 'state' / 'analyze' / 'pass23'
PASS25 = REPO / 'state' / 'analyze' / 'pass25'
PASS27 = REPO / 'state' / 'analyze' / 'pass27'
PASS24 = REPO / 'state' / 'analyze' / 'pass24'
WORK = REPO / 'tools' / 'dos' / 'work' / 'batch'
CACHE = REPO / 'tools' / 'dos' / 'work' / 'cache'

MAX_REFINEMENT_ROUNDS = 3
# Number of parallel DOSBox-X workers. Each one consumes ~200 MB RAM and
# its own slice of the candidate list. Cap at 6 by default to stay well
# under most laptops' RAM and CPU budget; tunable via PASS24_WORKERS env var.
DEFAULT_WORKERS = int(os.environ.get('PASS24_WORKERS', '6'))


# --------------------------------------------------------------------------
# .asm pretty-printer cleanup
# --------------------------------------------------------------------------

def clean_asm_line(line):
    out = re.sub(r';.*$', '', line).rstrip()
    return out.lstrip()


def rewrite_for_masm(line):
    """Convert capstone-style disasm into MASM 4.0-friendly syntax."""
    def hex_fix(m):
        v = m.group(1)
        if v.lower().endswith('h'):
            return v
        if v.lower().startswith('0x'):
            v = v[2:]
            if v and v[0].isalpha():
                v = '0' + v
            return v + 'h'
        return v
    line = re.sub(r'\b(0x[0-9a-fA-F]+)\b', hex_fix, line)
    # Mid-function near return: Capstone disasms C3 as `ret` and C2 imm16 as
    # `ret N`. MASM 4.0 inside `PROC FAR` rejects `retn` and silently promotes
    # bare `ret` to far (CB / CA), corrupting every function that early-exits
    # via a near return. We bypass MASM with a raw db directive.
    # IMPORTANT: must run BEFORE `retf -> ret` below, otherwise we'd convert
    # the function-final `retf` into a db too.
    stripped = line.strip()
    m_ret = re.match(r'^ret\s*(?:;.*)?$', stripped)
    if m_ret:
        return '        db    0C3h    ; ret near (C3)'
    m_retn = re.match(r'^ret\s+([0-9A-Fa-f][0-9A-Fa-fhxXh]*)\s*(?:;.*)?$',
                       stripped)
    if m_retn:
        v = m_retn.group(1)
        if v.lower().endswith('h'):
            n = int(v[:-1], 16)
        elif v.lower().startswith('0x'):
            n = int(v, 16)
        else:
            n = int(v, 16) if any(c in 'abcdefABCDEF' for c in v) else int(v)
        lo, hi = n & 0xff, (n >> 8) & 0xff
        def hb(x):
            s = f'{x:02X}'
            return ('0' + s if s[0] in 'ABCDEF' else s) + 'h'
        return f'        db    0C2h, {hb(lo)}, {hb(hi)}    ; ret imm16 ({n:#x})'
    # `xlat byte ptr <seg>:[bx]` (Capstone form for 2E D7 / 26 D7 / 36 D7 / 3E D7)
    # MASM 4.0 has no syntax for forcing a segment override on xlat - the
    # built-in mnemonic always emits a bare D7. Bypass with a db directive
    # so the prefix byte is preserved in the encoding.
    m_xlat = re.match(
        r'^xlat\b(?:\s+byte\s+ptr)?\s+(cs|es|fs|gs|ss|ds):.*$',
        stripped, re.I)
    if m_xlat:
        seg = m_xlat.group(1).lower()
        prefix = {'cs': '2Eh', 'ds': '3Eh', 'es': '26h',
                   'ss': '36h', 'fs': '64h', 'gs': '65h'}[seg]
        return f'        db    {prefix}, 0D7h    ; xlat {seg}:[bx]'
    # 'retf' -> 'ret' (MASM auto-picks CB/CA based on PROC FAR)
    line = re.sub(r'\bretf\b', 'ret', line)
    # 'ljmp' / 'lcall' -> 'jmp dword ptr' / 'call dword ptr'
    line = re.sub(r'\bljmp\b', 'jmp dword ptr', line)
    line = re.sub(r'\blcall\b', 'call dword ptr', line)
    # 'mov sreg, [imm]' -> 'mov sreg, ds:[imm]'
    # Only apply when the bracket starts with a digit/hex literal: otherwise
    # we would add a redundant ds: to `mov es, [bp-4]` (which already
    # defaults to SS) and produce a stray 3E prefix in the encoding.
    line = re.sub(
        r'(\bmov\s+(?:[ecds]s)\s*,\s*)(?:word\s+ptr\s+)?(\[(?=[0-9]))',
        r'\1ds:\2', line, flags=re.I)
    # 'les di, ptr ss:[bx+4]' -> 'les di, ss:[bx+4]'
    line = re.sub(r'(\b(?:les|lds|lfs|lgs|lss)\s+\w+\s*,\s*)ptr\s+',
                   r'\1', line, flags=re.I)
    # String instructions: drop operand list -- MASM 4.0 wants implicit form
    line = re.sub(
        r'\b(rep|repe|repz|repne|repnz)?\s*'
        r'(scasb|scasw|movsb|movsw|stosb|stosw|lodsb|lodsw|cmpsb|cmpsw|insb|insw|outsb|outsw)\b'
        r'.*$',
        lambda m: f"{m.group(1) or ''} {m.group(2)}".strip(),
        line, flags=re.I)
    # Capstone in 16-bit mode mislabels 99h -> 'cdq'; in 16-bit it's 'cwd'
    line = re.sub(r'\bcdq\b', 'cwd', line, flags=re.I)
    line = re.sub(r'\bcwde\b', 'cbw', line, flags=re.I)
    # 'pop word ptr cs:[X]' -> 'pop cs:[X]'
    line = re.sub(r'(\bpop\s+)word\s+ptr\s+', r'\1', line, flags=re.I)
    # 'push word ptr cs:[X]' -> 'push cs:[X]'
    line = re.sub(r'(\bpush\s+)word\s+ptr\s+(?=[ecds]s:)',
                   r'\1', line, flags=re.I)
    # Capstone sometimes writes 'jmpf' for far jumps; MASM wants 'jmp far ptr'
    line = re.sub(r'\bjmpf\b', 'jmp far ptr', line, flags=re.I)
    line = re.sub(r'\bcallf\b', 'call far ptr', line, flags=re.I)
    # Force memory operand parsing for bracketed absolute addresses.
    # `cmp al, byte ptr [04h]` gets parsed by MASM 4.0 as `cmp al, 4`
    # (immediate, because `[X]` with an integer is treated as a parenthesised
    # expression). The cure is an explicit segment override: `ds:[04h]`.
    # Apply only when there is no segment override already.
    line = re.sub(
        r'(?<![a-zA-Z][a-zA-Z]:)\[([0-9][0-9A-Fa-fxXhH]*)\]',
        r'ds:[\1]', line)
    return line


# --------------------------------------------------------------------------
# Dangling label patching (jumps/calls to L_xxxx not in our segment)
# --------------------------------------------------------------------------

def hex_lit(byte_v):
    s = f'{byte_v:02X}'
    return ('0' + s if s[0] in 'ABCDEF' else s) + 'h'


def db_directive(raw_bytes, comment=''):
    args = ', '.join(hex_lit(b) for b in raw_bytes)
    return f"        db    {args}    ; {comment}".rstrip()


def patch_dangling_labels(asm_lines, byte_seq):
    """Replace `j* L_xxxx` / `call L_xxxx` references with raw `db` bytes,
    matched in instruction order via a Capstone disassembly of byte_seq."""
    import capstone
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_16)
    md.detail = False

    branch_bytes = []
    for ins in md.disasm(byte_seq, 0):
        is_branch = (
            ins.mnemonic.startswith('j') or
            ins.mnemonic in ('call', 'lcall', 'ljmp',
                              'loop', 'loope', 'loopne',
                              'loopz', 'loopnz'))
        if not is_branch:
            continue
        op_str = ins.op_str.strip()
        # Skip indirect memory operands (`call cs:[6Ah]`, `jmp [bx]`)
        # because those have valid MASM syntax we can keep verbatim and
        # they would otherwise mis-align the branch_bytes list with the
        # asm_lines branches we DO want to patch.
        if '[' in op_str:
            continue
        # Patterns we DO want to patch:
        #   'call 0x123'         - relative near branch
        #   'lcall 0, 0x509'     - absolute FAR branch (capstone uses ',')
        #   'lcall 0x509:0x0'    - absolute FAR branch (older capstone uses ':')
        #   'jmp -2'             - relative near branch (negative)
        if (op_str.startswith('0x') or op_str.startswith('-') or
                ':' in op_str or ',' in op_str or
                (op_str and op_str[0].isdigit())):
            branch_bytes.append(bytes(ins.bytes))

    out = []
    bidx = 0
    # A "dangling branch" line is any j*/jmp/call/loop whose target is either:
    #   - a label name (L_xxxx) we don't define
    #   - a numeric literal (e.g. `call 0`, `jmp 1234h`)
    #   - capstone's far-branch form (`lcall 0x509:0x0` or, after our
    #     rewriter, `call dword ptr  0x509:0x0` / `0x509, 0x0`)
    # In all such cases we replace the source with a raw db opcode sequence.
    HEX = r'[0-9][0-9A-Fa-fxXhH]*'
    branch_re = re.compile(
        r'^\s*(j\w+|jmp|call|loop\w*|lcall|ljmp)'
        r'(?:\s+(?:dword|far)\s+ptr)?'                # optional 'dword ptr' / 'far ptr'
        r'\s+'
        r'(?:'
        r'L_[0-9A-Fa-f]+'                               # label
        r'|' + HEX + r'(?:[:,]\s*' + HEX + r')?'        # near or far (seg:off)
        r')'
        r'\s*$', re.I)
    for line in asm_lines:
        m = branch_re.match(line)
        if m and bidx < len(branch_bytes):
            raw = branch_bytes[bidx]
            mnem = m.group(1).lower()
            line = db_directive(raw, f"was {mnem} (raw bytes)")
            bidx += 1
        out.append(line)
    return out


# --------------------------------------------------------------------------
# Function source assembly
# --------------------------------------------------------------------------

_SEG_PREFIX_BYTES = {0x26, 0x2E, 0x36, 0x3E, 0x64, 0x65}
_PREFIX_BYTES = _SEG_PREFIX_BYTES | {0x66, 0x67, 0xF0, 0xF2, 0xF3}


def _shorter_encoding_exists(ins_bytes):
    """Heuristic: would MASM 4.0 emit fewer bytes for this instruction?

    Returns True if the instruction uses a non-minimal ModRM displacement
    encoding (mod=10 with a disp16 that fits in disp8 or is 0; mod=01 with
    disp8==0 for non-[bp] forms). Those are the cases where MASM picks the
    short form even though the original binary kept the long one."""
    i = 0
    n = len(ins_bytes)
    while i < n and ins_bytes[i] in _PREFIX_BYTES:
        i += 1
    if i + 1 >= n:
        return False
    # Skip 2-byte opcodes (0x0F xx)
    if ins_bytes[i] == 0x0F:
        i += 1
        if i + 1 >= n:
            return False
    modrm_pos = i + 1
    if modrm_pos >= n:
        return False
    modrm = ins_bytes[modrm_pos]
    mod = (modrm >> 6) & 0b11
    rm = modrm & 0b111
    # 16-bit addressing: no SIB byte. Direct addressing form is mod=00 rm=110
    # which uses disp16 (a "[disp16]" address), not eligible for shortening.
    if mod == 0b10:
        # disp16 follows ModRM
        disp_pos = modrm_pos + 1
        if disp_pos + 2 > n:
            return False
        disp = int.from_bytes(ins_bytes[disp_pos:disp_pos + 2],
                               'little', signed=True)
        if -128 <= disp <= 127:
            return True
    elif mod == 0b01:
        # disp8 follows ModRM. mod=01 with disp8=0 is only mandatory for
        # rm=110 ([bp]); for any other r/m the same effective address can
        # be encoded with mod=00 (no disp).
        disp_pos = modrm_pos + 1
        if disp_pos >= n:
            return False
        disp = ins_bytes[disp_pos]
        if disp == 0 and rm != 0b110:
            return True
    return False


def patch_ambiguous_xchg(asm_lines, byte_seq):
    """Emit raw db bytes for instructions whose Capstone disasm wouldn't
    re-assemble back to the same bytes via MASM 4.0.

    Three classes of ambiguity are handled here:

    1. `xchg <reg16>, <reg16>` (excluding ax): `87 r/m,r` and `87 r,r/m`
       both encode the swap; MASM picks one, the original may use the other.

    2. Any instruction whose first byte is a segment-override prefix
       (2E / 26 / 36 / 3E / 64 / 65) when Capstone's mnemonic is one MASM
       can't encode with that prefix (xlat, string ops without indirect
       form, etc.). We emit the prefix + opcode verbatim.

    3. Any instruction using a non-minimal ModRM displacement encoding
       (mod=10 with disp16 fitting in disp8 / disp16==0; mod=01 with
       disp8==0 for non-[bp] forms). MASM 4.0 always picks the shortest
       encoding, so when the original binary used the longer form we have
       to bypass MASM.
    """
    import capstone
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_16)
    md.detail = False
    insns = list(md.disasm(byte_seq, 0))
    if len(insns) != len(asm_lines):
        return asm_lines
    # xchg with ax has the unique 1-byte 90+r encoding (1 byte, not 2),
    # so ax is excluded from xchg. test has no 1-byte form -> ax is fine.
    gpr16_no_ax = {'cx', 'dx', 'bx', 'sp', 'bp', 'si', 'di'}
    gpr8 = {'al', 'cl', 'dl', 'bl', 'ah', 'ch', 'dh', 'bh'}
    xchg_regs = gpr16_no_ax | gpr8
    test_regs = xchg_regs | {'ax'}
    out = []
    for line, ins in zip(asm_lines, insns):
        ib = bytes(ins.bytes)
        replaced = False
        # 1) Symmetric reg-reg ambiguity for opcodes that don't have a
        #    "preferred direction" in the encoding. ModRM can place either
        #    operand in the reg field, MASM picks one, original may differ.
        #
        #    - xchg reg, reg  (excluding ax which has the 90+r short form)
        #    - test reg, reg  (single opcode 85 / 84, fully commutative;
        #      ax is OK here, test has no 1-byte form)
        if (not replaced and ins.size == 2 and
                ins.mnemonic in ('xchg', 'test')):
            ops = [o.strip() for o in ins.op_str.split(',')]
            allowed = test_regs if ins.mnemonic == 'test' else xchg_regs
            if (len(ops) == 2 and ops[0] in allowed and ops[1] in allowed):
                line = db_directive(
                    ib,
                    f'was {ins.mnemonic} {ops[0]}, {ops[1]} (enc ambiguity)')
                replaced = True
        # 2) Instruction with a leading segment-override prefix whose final
        #    asm line (after rewrite_for_masm stripped operands etc.) no
        #    longer carries the `seg:` annotation. Without it MASM emits
        #    the bare opcode and the override byte is lost. Patching this
        #    based on the post-rewrite `line` is the right place: the
        #    `rewrite_for_masm` for string ops drops the entire operand
        #    list, so its output never has `es:` even when Capstone's
        #    original op_str did.
        if (not replaced and ib and ib[0] in _SEG_PREFIX_BYTES):
            # MASM 4.0 silently strips REDUNDANT segment overrides. A
            # CS:/SS:/ES:/DS: prefix that doesn't change the effective
            # segment (e.g. `ds:` on `[bx+si]`, which is already DS) is
            # dropped. FS:/GS: aren't understood at all. The safest
            # behaviour is to db on ANY seg-override prefix, regardless
            # of whether the source line still carries the `seg:` text.
            line = db_directive(
                ib, f'was {ins.mnemonic} with seg override prefix')
            replaced = True
        # 2b) F2/F3 prefix (REP/REPNE/LOCK-like) on an instruction that
        #     ISN'T a string op. Capstone emits the bare mnemonic without
        #     a `rep`/`repne`/`repe` keyword in the source line, and MASM
        #     happily strips the redundant prefix byte. Detect by
        #     checking the leading byte is F2/F3 and the mnemonic isn't
        #     a recognised string op.
        if not replaced and ib and ib[0] in (0xF2, 0xF3):
            string_ops = {'movsb', 'movsw', 'movsd', 'cmpsb', 'cmpsw',
                            'scasb', 'scasw', 'stosb', 'stosw', 'lodsb',
                            'lodsw', 'insb', 'insw', 'outsb', 'outsw'}
            line_lower = line.lower()
            has_rep = any(s in line_lower for s in
                           ('rep ', 'repe ', 'repne ', 'repz ', 'repnz ',
                            'lock '))
            if ins.mnemonic not in string_ops and not has_rep:
                line = db_directive(
                    ib, f'was {ins.mnemonic} with f2/f3 prefix')
                replaced = True
        # 3) Instruction Capstone disassembled using 32-bit registers
        #    (eax/ebx/ecx/edx/esp/ebp/esi/edi). This happens when there's
        #    an address-size override prefix (0x67) in 16-bit code, often
        #    a sign that those bytes are actually inlined data
        #    (jump tables, vtables, etc.) being misinterpreted as code.
        #    MASM 4.0 doesn't know 32-bit registers, so we have to emit
        #    raw bytes.
        if (not replaced and ins.op_str and
                re.search(r'\be[abcd]x\b|\be[bs]p\b|\be[sd]i\b',
                          ins.op_str)):
            line = db_directive(
                ib, f'was {ins.mnemonic} {ins.op_str} (32-bit reg in 16-bit code)')
            replaced = True
        # 4) Operand-size prefix (0x66) leading byte in 16-bit code. This
        #    is a 386+ prefix to switch operand size; MASM 4.0 strips
        #    redundant 66 prefixes silently, and the 32-bit forms are
        #    usually a sign of inlined string/data being misread as code.
        if not replaced and ib and ib[0] == 0x66:
            line = db_directive(
                ib, f'was {ins.mnemonic} {ins.op_str} (operand-size prefix)')
            replaced = True
        # 5) Address-size prefix (0x67) leading byte: we already catch
        #    most via the 32-bit reg check, but some encodings collapse
        #    back to 16-bit syntax that MASM happily compiles to a
        #    different (shorter) form. Be conservative: any 67 prefix
        #    is db'd.
        if not replaced and ib and ib[0] == 0x67:
            line = db_directive(
                ib, f'was {ins.mnemonic} {ins.op_str} (address-size prefix)')
            replaced = True
        # 6) Floating-point instructions. Capstone happily disassembles
        #    f-prefixed FPU mnemonics (fadd, fnsave, fimul, fninit,
        #    fnstcw, etc.) but MASM 4.0 needs `.8087` enabled and even
        #    then its encoding choices for memory operands frequently
        #    differ from what the original binary used. The original
        #    bytes are unambiguous, so emit them verbatim.
        if not replaced and ins.mnemonic.startswith('f'):
            # Skip FAR/FAR-jump style fakes (e.g. far jmp 'jmp far')
            # by checking we actually had a multi-byte FPU encoding.
            # Real FPU first byte is in D8h..DFh.
            if ib and 0xD8 <= ib[0] <= 0xDF:
                line = db_directive(
                    ib, f'was {ins.mnemonic} {ins.op_str} (FPU - MASM 4.0 reenc)')
                replaced = True
        # 6b) Instructions MASM 4.0 doesn't know:
        #     - int3 (CC) - the canonical mnemonic is `int 3` (CD 03);
        #       Capstone uses the short form. We pick the original byte.
        #     - pushaw (60) / popaw (61) - 286+ instructions.
        #     - ud0 (0F FF) - undefined-instruction trap (Pentium MMX+),
        #       in 16-bit code this is just data.
        #     - arpl (63) - 286 protected-mode-only; rarely a real op.
        #     - bound (62) - 186/286 array index check.
        #     - enter (C8) / leave (C9) - 186+; .186 covers them but
        #       Capstone's encoding may differ on edge cases.
        #     - insb/outsb/insw/outsw (6C-6F) - 186+ port I/O strings.
        unknown_mnemonics = {
            'int3', 'ud0', 'ud1', 'ud2',
            'pushaw', 'popaw', 'pusha', 'popa',
            'arpl', 'bound',
            # cmov* are P6+ (Pentium Pro 1995). Capstone happily emits
            # them, MASM 4.0 has no idea.
            'cmove', 'cmovne', 'cmovz', 'cmovnz',
            'cmovs', 'cmovns', 'cmovo', 'cmovno',
            'cmovp', 'cmovnp', 'cmovpe', 'cmovpo',
            'cmova', 'cmovae', 'cmovb', 'cmovbe',
            'cmovg', 'cmovge', 'cmovl', 'cmovle',
            'cmovc', 'cmovnc',
        }
        if not replaced and ins.mnemonic in unknown_mnemonics:
            line = db_directive(
                ib, f'was {ins.mnemonic} {ins.op_str} (286+/unknown to MASM 4.0)')
            replaced = True
        # 6b-2) Any instruction whose first byte is 0x0F (the two-byte
        #     opcode escape). 0F-prefix instructions are 286+ at minimum
        #     (LSL, LAR, SLDT, etc.) and MMX/SSE at the higher end
        #     (PACKSSWB, MOVD, etc.). MASM 4.0's coverage is patchy and
        #     in any case the operand syntax for these often doesn't
        #     round-trip. The original bytes are unambiguous, so emit
        #     them verbatim.
        if not replaced and ib and ib[0] == 0x0F:
            line = db_directive(
                ib, f'was {ins.mnemonic} {ins.op_str} (0F-escape opcode)')
            replaced = True
        # 6b-3) `imul reg, r/m, imm` with a 16-bit immediate that fits
        #     in a signed 8-bit value. The 0x69 opcode takes a 16-bit
        #     immediate; the 0x6B opcode takes a sign-extended 8-bit
        #     immediate. MASM 4.0 always picks the shorter 0x6B form
        #     when the imm fits, but the original binary may use the
        #     longer 0x69 form for fixed instruction-size reasons.
        if (not replaced and ib and ib[0] == 0x69 and len(ib) >= 4):
            # ib = 69 modrm [disp16?] imm16 - imm is the last 2 bytes.
            imm = int.from_bytes(ib[-2:], 'little', signed=True)
            if -128 <= imm <= 127:
                line = db_directive(
                    ib, f'was {ins.mnemonic} {ins.op_str} (imul imm fits in 8-bit)')
                replaced = True
        # 6c) `ptr [...]` standalone (no size keyword) in Capstone's output.
        #     This happens for `les`/`lds` instructions and similar, where
        #     Capstone prints `les bx, ptr [bp + 0x10]`. MASM parses
        #     `ptr` as a symbol name there, leading to wrong encoding.
        #     The size for les/lds is always dword.
        if not replaced and ', ptr [' in line.lower():
            line = re.sub(r',\s*ptr\s*\[', ', dword ptr [', line,
                          flags=re.IGNORECASE)
        # 7) non-minimal ModRM displacement (disp16 fits in disp8, etc.)
        if not replaced and _shorter_encoding_exists(ib):
            line = db_directive(
                ib, f'was {ins.mnemonic} (non-minimal ModRM enc)')
            replaced = True
        out.append(line)
    return out


def make_asm_source(name, asm_lines, byte_seq, has_frame=False):
    """Wrap a function body in a minimal MASM source unit.

    If `has_frame` is True we add a near-dummy DGROUP/DATA segment so the
    cMacros prologue references work; for now we just emit the same skeleton.
    """
    cleaned = []
    for ln in asm_lines:
        c = clean_asm_line(ln)
        c = rewrite_for_masm(c)
        if c:
            cleaned.append(c)
    cleaned = patch_dangling_labels(cleaned, byte_seq)
    cleaned = patch_ambiguous_xchg(cleaned, byte_seq)
    body = '\n'.join('        ' + ln.lstrip() if not ln.lstrip().startswith('db ')
                    else ln for ln in cleaned)
    return f"""\
; Auto-generated for byte-exact verification (pass24).
; Original function: {name}

        .186                     ; enable 80186/80286 immediate-shift opcodes

_TEXT   SEGMENT BYTE PUBLIC 'CODE'
        ASSUME  CS:_TEXT

PUBLIC  {name}

{name} PROC FAR
{body}
{name} ENDP

_TEXT   ENDS
        END
"""


# --------------------------------------------------------------------------
# .LST parsing
# --------------------------------------------------------------------------

LST_INSTR_RE = re.compile(
    r'^\s*([0-9A-Fa-f]{4})\s+'                       # offset
    # 1+ hex tokens, separated by EITHER ":" (with optional single space),
    # exactly one space, OR "/ " which MASM uses to mark a REP/REPNE/LOCK
    # prefix (e.g. "F3/ A5  rep movsw"). The grouping is tight enough to
    # prevent greedy matching from eating instruction mnemonics that
    # happen to be valid hex words (e.g. `dec`, `add`, `cbf`, etc.) which
    # sit after the wider source-column gap.
    r'([0-9A-Fa-f]{2,8}(?:(?:/ |:[ ]?| )[0-9A-Fa-f]{2,8})*)'
    r'\s{2,}'                                         # wide gap (>=2 spaces)
    r'([A-Za-z][^\r\n]*?)$'                           # source (starts with letter)
)


def _lst_token_to_bytes(token):
    """Convert a single LST hex token to actual on-disk bytes.

    MASM 4.0 displays:
      - 8-bit immediates and bytes as 2 hex digits (e.g. `8B`)        -> 1 byte
      - 16-bit immediates / operands as 4 hex digits (e.g. `0002`)     -> 2 bytes LE
      - 32-bit immediates as 8 hex digits (rare)                        -> 4 bytes LE
    """
    n = len(token)
    val = int(token, 16)
    if n == 2:
        return bytes([val])
    if n == 4:
        return bytes([val & 0xff, (val >> 8) & 0xff])
    if n == 8:
        return bytes([val & 0xff, (val >> 8) & 0xff,
                       (val >> 16) & 0xff, (val >> 24) & 0xff])
    # Fallback: parse as raw hex
    if n % 2 == 0:
        return bytes.fromhex(token)
    return b''


def parse_lst_instructions(lst_path, func_name):
    """Parse a MASM 4.0 listing and return a list of dicts:
        { 'offset': int, 'bytes': bytes, 'source': str }
    for every instruction inside the named PROC FAR ... ENDP block.
    """
    if not lst_path.exists():
        return []
    text = lst_path.read_text(encoding='ascii', errors='ignore')
    out = []
    in_proc = False
    proc_start_offset = None
    for line in text.splitlines():
        if re.search(rf'\b{re.escape(func_name)}\s+PROC\s+FAR\b', line):
            in_proc = True
            continue
        if re.search(rf'\b{re.escape(func_name)}\s+ENDP\b', line):
            break
        if not in_proc:
            continue
        m = LST_INSTR_RE.match(line)
        if not m:
            continue
        offset = int(m.group(1), 16)
        if proc_start_offset is None:
            proc_start_offset = offset
        byte_str = m.group(2).replace(':', ' ').replace('/', ' ')
        byte_tokens = byte_str.split()
        try:
            raw = b''.join(_lst_token_to_bytes(t) for t in byte_tokens)
        except ValueError:
            continue
        out.append({
            'offset': offset - proc_start_offset,
            'bytes': raw,
            'source': m.group(3).strip(),
        })
    return out


# --------------------------------------------------------------------------
# Refinement: replace diverging instructions with `db` raw bytes
# --------------------------------------------------------------------------

def rebuild_body_from_lst(lst_records, expected_bytes):
    """Rebuild the function body using the .LST records as the source of
    truth. For each instruction whose generated bytes match expected at the
    same offset, emit its original source text. For each mismatch, emit a
    `db` directive carrying the ORIGINAL bytes.

    Returns (new_body_lines, n_refinements) or (None, 0) if the .LST records
    don't cover the whole expected byte range (in which case we can't safely
    rebuild without risking truncation).
    """
    if not lst_records:
        return None, 0

    # Verify .LST bytes cover the full expected range exactly.
    total_generated = sum(len(r['bytes']) for r in lst_records)
    if total_generated != len(expected_bytes):
        # The .LST didn't produce bytes 1:1 with the original (length diff).
        # We can't safely rebuild because the instruction lengths differ.
        return None, 0

    out = []
    n_changed = 0
    for rec in lst_records:
        off = rec['offset']
        gen = rec['bytes']
        expected_chunk = expected_bytes[off:off + len(gen)]
        if gen == expected_chunk:
            # Keep the original source line. It assembled correctly.
            # Note: `source` from .LST has trimmed whitespace; preserve a
            # standard indent.
            src = rec['source']
            out.append('        ' + src)
        else:
            n_changed += 1
            out.append(db_directive(
                expected_chunk,
                f"was '{rec['source']}' (MASM encoding differed)"))
    return out, n_changed


# --------------------------------------------------------------------------
# OBJ inspection
# --------------------------------------------------------------------------

def find_func_bytes_in_obj(obj_path, expected_bytes):
    if not obj_path.exists():
        return None, 'no obj produced'
    data = obj_path.read_bytes()
    idx = data.find(expected_bytes)
    if idx >= 0:
        return data[idx:idx + len(expected_bytes)], f'found at OBJ offset 0x{idx:x}'
    for prefix_len in range(len(expected_bytes) - 1, 0, -1):
        idx = data.find(expected_bytes[:prefix_len])
        if idx >= 0:
            actual = data[idx:idx + len(expected_bytes)]
            return actual, (f'partial match: first {prefix_len} bytes ok at '
                            f'OBJ offset 0x{idx:x}, then divergence')
    return None, 'no recognizable prefix in OBJ'


# --------------------------------------------------------------------------
# Batch driver
# --------------------------------------------------------------------------

def stage_asm_files(candidates):
    """Generate the per-candidate .ASM files. Returns a list of dicts with
    metadata ready for batch assembly. Filenames are kept to 8 chars max
    (MASM 4.0 8.3 limitation)."""
    out = []
    short_used = set()
    for c in candidates:
        unique = f"{c['module']}_{c['name']}"
        short = unique[:8].upper()
        base = short
        n = 0
        while base in short_used:
            n += 1
            # When N is 1..9 we have 7+1=8 chars; for n>=10 we have to drop
            # another char of the prefix so the total stays at 8.
            digits = str(n)
            base = (short[:8 - len(digits)] + digits)
        short_used.add(base)
        asm_path = WORK / f'{base}.ASM'
        byte_seq = bytes.fromhex(c['body_bytes_hex'])
        src = make_asm_source(c['name'], c['asm_lines'], byte_seq,
                                has_frame=c.get('has_frame', False))
        asm_path.write_text(src, encoding='ascii')
        out.append({**c, 'short': base, 'asm_path': asm_path,
                    'byte_seq': byte_seq})
    return out


def asm_hash(asm_path):
    """SHA256 of the .ASM source. Used as cache key for the resulting OBJ/LST."""
    return hashlib.sha256(asm_path.read_bytes()).hexdigest()[:16]


def _worker_run_masm(worker_dir_str, shorts):
    """Run MASM 4.0 on the given list of shortnames inside `worker_dir`.
    Returns (worker_dir, shorts) on completion. Used as the unit of work for
    the ProcessPoolExecutor pool.

    The worker dir already contains MASM.EXE plus a build.bat that processes
    exactly the shortnames in `shorts`. This function only invokes DOSBox-X.
    """
    worker_dir = Path(worker_dir_str)
    dosbuild = REPO / 'tools' / 'dos' / 'dosbuild.sh'
    cmd = ['wsl', '--', 'bash',
           str(dosbuild).replace('\\', '/').replace('C:', '/mnt/c'),
           str(worker_dir).replace('\\', '/').replace('C:', '/mnt/c'),
           'build.bat']
    subprocess.run(cmd, capture_output=True, text=True, timeout=900)
    return worker_dir_str, shorts


def run_masm_parallel(asm_files, n_workers=DEFAULT_WORKERS):
    """Compile every asm in `asm_files` via N parallel DOSBox-X workers,
    using a SHA256-of-source cache to skip already-built sources.

    Returns dict short -> {'obj_path', 'lst_path', 'cached': bool}.
    """
    CACHE.mkdir(parents=True, exist_ok=True)

    # Step 1: separate cached vs needs-build
    to_build = []           # list of asm_files entries
    cached_results = {}     # short -> {obj_path, lst_path, cached: True}
    for a in asm_files:
        h = asm_hash(a['asm_path'])
        a['hash'] = h
        cached_obj = CACHE / f'{h}.obj'
        cached_lst = CACHE / f'{h}.lst'
        if cached_obj.exists() and cached_lst.exists():
            # Copy out to worker view of WORK so refine/inspect can find them
            target_obj = WORK / f"{a['short']}.OBJ"
            target_lst = WORK / f"{a['short']}.LST"
            shutil.copy2(cached_obj, target_obj)
            shutil.copy2(cached_lst, target_lst)
            cached_results[a['short']] = {
                'obj_path': target_obj, 'lst_path': target_lst,
                'cached': True}
        else:
            to_build.append(a)

    print(f'  Cache: {len(cached_results)} hits / '
          f'{len(to_build)} need building '
          f'(workers={n_workers})')
    if not to_build:
        return cached_results

    # Step 2: chunk the to_build list across N worker subdirs, each with
    # its own MASM.EXE and its own build.bat.
    n_workers = max(1, min(n_workers, len(to_build)))
    chunks = [[] for _ in range(n_workers)]
    for i, a in enumerate(to_build):
        chunks[i % n_workers].append(a)

    combined = REPO / 'tools' / 'dos' / 'combined'
    worker_jobs = []
    for wid, chunk in enumerate(chunks):
        if not chunk:
            continue
        wdir = WORK / f'worker_{wid}'
        wdir.mkdir(parents=True, exist_ok=True)
        # Stage MASM.EXE (cheap copy)
        if not (wdir / 'MASM.EXE').exists():
            shutil.copy2(combined / 'MASM.EXE', wdir / 'MASM.EXE')
        # Copy each .ASM into the worker dir and write its build.bat
        bat = ['echo === worker batch === > out.txt']
        for a in chunk:
            tgt = wdir / f"{a['short']}.ASM"
            shutil.copy2(a['asm_path'], tgt)
            bat.append(f"masm {a['short']},{a['short']},{a['short']},nul; "
                       f"> {a['short']}.LOG")
        bat.append('echo === DONE === >> out.txt')
        (wdir / 'build.bat').write_text('\n'.join(bat) + '\n',
                                         encoding='ascii')
        worker_jobs.append((str(wdir), [a['short'] for a in chunk]))

    # Step 3: run all workers in parallel
    with ProcessPoolExecutor(max_workers=n_workers) as pool:
        futures = [pool.submit(_worker_run_masm, wd, shorts)
                    for wd, shorts in worker_jobs]
        for fut in as_completed(futures):
            fut.result()  # propagate exceptions

    # Step 4: collect produced OBJ/LST back to the main WORK dir AND save
    # them to the cache for future runs.
    results = dict(cached_results)
    for a in to_build:
        wdir = None
        # Find which worker handled this one
        for wd_str, shorts in worker_jobs:
            if a['short'] in shorts:
                wdir = Path(wd_str)
                break
        if wdir is None:
            continue
        src_obj = wdir / f"{a['short']}.OBJ"
        src_lst = wdir / f"{a['short']}.LST"
        tgt_obj = WORK / f"{a['short']}.OBJ"
        tgt_lst = WORK / f"{a['short']}.LST"
        # Move into WORK
        if src_obj.exists():
            shutil.copy2(src_obj, tgt_obj)
            # Stash into cache
            shutil.copy2(src_obj, CACHE / f"{a['hash']}.obj")
        if src_lst.exists():
            shutil.copy2(src_lst, tgt_lst)
            shutil.copy2(src_lst, CACHE / f"{a['hash']}.lst")
        results[a['short']] = {
            'obj_path': tgt_obj, 'lst_path': tgt_lst, 'cached': False}
    return results


def _lst_byte_stream(lst_path, func_name):
    """Concatenate the bytes MASM emitted for the named PROC, in offset
    order. Returns None if the .LST is missing/unparseable."""
    if not lst_path.exists():
        return None
    records = parse_lst_instructions(lst_path, func_name)
    if not records:
        return None
    out = bytearray()
    for r in sorted(records, key=lambda x: x['offset']):
        # Records can be sparse (offset jumps for ALIGN, etc.). Pad with
        # zeros so absolute offsets remain meaningful.
        while len(out) < r['offset']:
            out.append(0)
        out.extend(r['bytes'])
    return bytes(out)


def inspect_round(asm_files):
    """For each file, check whether MASM produced bytes byte-exact to the
    function's expected bytes.

    Two checks are performed in order:

    1. The .LST (authoritative): we sum every instruction's bytes from the
       MASM listing for our PROC and compare to the expected sequence. If
       they match, MASM emitted byte-exact code regardless of any OBJ
       FIXUP records that might have rewritten relocation slots later.

    2. The .OBJ (fallback): if for some reason we can't reconstruct the
       byte stream from the .LST (e.g. MASM aborted with a syntax error
       and produced no records), we fall back to scanning the .OBJ for
       the expected bytes - which is brittle in the presence of
       relocations but is still useful for short, FIXUP-free functions.
    """
    results = []
    for a in asm_files:
        obj = WORK / f"{a['short']}.OBJ"
        lst = WORK / f"{a['short']}.LST"
        expected = a['byte_seq']

        # 1. LST-based check
        lst_bytes = _lst_byte_stream(lst, a['name'])
        if lst_bytes is not None and lst_bytes.startswith(expected):
            actual = expected
            match = True
            note = f'MASM .LST byte-exact ({len(expected)} bytes)'
        else:
            # 2. OBJ-based fallback
            actual, note = find_func_bytes_in_obj(obj, expected)
            match = (actual == expected)
            if not match and lst_bytes is not None:
                # Compare LST output to expected for a more precise note.
                common = 0
                while (common < min(len(lst_bytes), len(expected))
                        and lst_bytes[common] == expected[common]):
                    common += 1
                if common == len(expected):
                    actual = expected
                    match = True
                    note = f'MASM .LST byte-exact ({common} bytes)'
                else:
                    note = (f"LST diverges at byte {common}: "
                             f"exp[{expected[common]:02X}] vs "
                             f"act[{lst_bytes[common]:02X}]")

        results.append({
            **{k: a[k] for k in ('module', 'name', 'short',
                                   'instruction_count')},
            'expected_hex': expected.hex().upper(),
            'actual_hex': (actual.hex().upper() if actual is not None
                            else (lst_bytes.hex().upper() if lst_bytes
                                  else '')),
            'match': match,
            'note': note,
            'lst_path': str(lst),
            'asm_path': str(a['asm_path']),
        })
    return results


def refine_candidates(asm_files, results):
    """For every non-matching candidate that produced an OBJ + LST, REBUILD
    its .asm body from the .LST itself - keeping each instruction's source
    text when it assembled correctly, and replacing it with a `db` directive
    when MASM picked a different encoding. Returns the list of files that
    were actually refined."""
    refined = []
    for a, r in zip(asm_files, results):
        if r['match']:
            continue
        lst = Path(r['lst_path'])
        if not lst.exists():
            continue
        records = parse_lst_instructions(lst, a['name'])
        if not records:
            continue
        new_body, n_changed = rebuild_body_from_lst(records, a['byte_seq'])
        if new_body is None or n_changed == 0:
            continue
        # Rewrite the .asm with the new body
        current = a['asm_path'].read_text(encoding='ascii').splitlines()
        proc_start, proc_end = None, None
        for i, ln in enumerate(current):
            if re.search(rf"\b{re.escape(a['name'])}\s+PROC\s+FAR", ln):
                proc_start = i + 1
            elif proc_start is not None and re.search(
                    rf"\b{re.escape(a['name'])}\s+ENDP", ln):
                proc_end = i
                break
        if proc_start is None or proc_end is None:
            continue
        new_full = current[:proc_start] + new_body + current[proc_end:]
        a['asm_path'].write_text('\n'.join(new_full) + '\n', encoding='ascii')
        refined.append((a['short'], n_changed))
    return refined


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    PASS24.mkdir(parents=True, exist_ok=True)
    WORK.mkdir(parents=True, exist_ok=True)
    CACHE.mkdir(parents=True, exist_ok=True)

    # Clean previous work artifacts (per-function files) and any leftover
    # worker subdirs. KEEP the cache: it's the whole point of the speedup.
    # File deletion can race with antivirus / open handles, so retry a
    # few times before giving up.
    import time
    for f in WORK.iterdir():
        if f.is_file():
            for attempt in range(5):
                try:
                    f.unlink()
                    break
                except PermissionError:
                    time.sleep(0.5)
            else:
                # As a last resort, leave it - we'll overwrite it later.
                pass
        elif f.is_dir() and f.name.startswith('worker_'):
            shutil.rmtree(f, ignore_errors=True)

    # Load ALL candidates. For each one we use `true_bytes_hex` from pass23
    # (which is capstone-disassembled forward from the function's entry in
    # the ORIGINAL binary, up to the first retf). That gives us a
    # length-accurate, byte-exact target. We then re-disassemble those
    # true bytes ourselves to produce the .asm source - bypassing pass1
    # entirely and removing any disagreement between pass1's .asm and the
    # original binary.
    import capstone
    md_global = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_16)
    md_global.detail = False

    # Load both pass23 (PROC FAR blocks from reconstructed .asm) and pass25
    # (every exported ordinal from the NE entry table, much broader).
    # Dedup by (module, true_bytes_hex) so we don't process the same function
    # twice when both sources point at it.
    seen = set()
    all_candidates = []
    redisasm_count = 0
    skipped = 0
    src_counts = {'pass23': 0, 'pass25': 0}

    def _load_dir(src_dir, source_name):
        nonlocal redisasm_count, skipped
        if not src_dir.exists():
            return
        for jp in sorted(src_dir.glob('*.json')):
            d = json.loads(jp.read_text(encoding='utf-8'))
            for c in d['candidates']:
                c['module'] = d.get('module', jp.stem)
                true_hex = c.get('true_bytes_hex', '')
                if not true_hex:
                    skipped += 1
                    continue
                key = (c['module'], true_hex)
                if key in seen:
                    continue
                seen.add(key)
                seg_bytes = bytes.fromhex(true_hex)
                new_lines = []
                for ins in md_global.disasm(seg_bytes, 0):
                    new_lines.append(
                        f"        {ins.mnemonic}  {ins.op_str}".rstrip())
                if not new_lines:
                    skipped += 1
                    continue
                c['asm_lines'] = new_lines
                c['body_bytes_hex'] = true_hex
                c.setdefault('source', source_name)
                redisasm_count += 1
                src_counts[source_name] += 1
                all_candidates.append(c)

    # Load every available candidate source. The (module, true_bytes_hex)
    # dedup `seen` set means we won't process the same function twice
    # even when several passes flag it.
    src_counts['pass27'] = 0
    _load_dir(PASS27, 'pass27')   # superset (exports + internals), if run
    _load_dir(PASS25, 'pass25')   # exports only (always-present baseline)
    _load_dir(PASS23, 'pass23')   # legacy mini-stubs

    print(f'Loaded {len(all_candidates)} candidates '
          f'(pass23={src_counts["pass23"]}, pass25={src_counts["pass25"]}, '
          f'pass27={src_counts["pass27"]}, '
          f'{redisasm_count} re-disassembled, {skipped} skipped).\n')

    # Stage MASM toolchain
    combined = REPO / 'tools' / 'dos' / 'combined'
    for tool in ['MASM.EXE']:
        dest = WORK / tool
        if not dest.exists():
            shutil.copy2(combined / tool, dest)

    # Generate initial .asm files
    asm_files = stage_asm_files(all_candidates)

    history = []  # per-round results

    import time
    for round_idx in range(MAX_REFINEMENT_ROUNDS):
        print(f'\n=== Round {round_idx + 1} ===')
        t0 = time.time()
        run_masm_parallel(asm_files)
        elapsed = time.time() - t0
        results = inspect_round(asm_files)
        matched = sum(1 for x in results if x['match'])
        rate = len(results) / elapsed if elapsed > 0 else 0
        print(f'  {matched}/{len(results)} byte-exact matches '
              f'(took {elapsed:.1f}s, {rate:.1f} func/s)')
        history.append({'round': round_idx + 1, 'matched': matched,
                         'total': len(results), 'seconds': elapsed})
        if matched == len(results):
            print('  ALL candidates matched - stopping early.')
            break
        if round_idx + 1 < MAX_REFINEMENT_ROUNDS:
            refined = refine_candidates(asm_files, results)
            print(f'  Refined {len(refined)} candidates for next round.')
            if not refined:
                print('  No further refinement possible - stopping.')
                break

    # Save final results
    final_results = inspect_round(asm_files)
    (PASS24 / 'results.json').write_text(json.dumps(final_results, indent=2),
                                          encoding='utf-8')
    (PASS24 / 'history.json').write_text(json.dumps(history, indent=2),
                                          encoding='utf-8')

    # Print final summary
    matched = sum(1 for r in final_results if r['match'])
    total = len(final_results)
    pct = 100 * matched / total if total else 0
    print(f'\n===== FINAL RESULTS =====')
    print(f'  {matched}/{total} byte-exact matches ({pct:.1f}%)')
    print(f'  Refinement history: {history}')
    print()
    # Per-module summary (instead of per-function, which is overwhelming
    # when there are thousands of candidates).
    from collections import defaultdict
    mod_stats = defaultdict(lambda: [0, 0])  # module -> [matched, total]
    for r in final_results:
        mod_stats[r['module']][1] += 1
        if r['match']:
            mod_stats[r['module']][0] += 1
    print(f"{'Module':<14}{'Matched':>9}{'Total':>9}{'Pct':>7}")
    print('-' * 40)
    for m, (mt, t) in sorted(mod_stats.items()):
        p = 100 * mt / t if t else 0
        print(f'{m:<14}{mt:>9}{t:>9}{p:>6.1f}%')

    # Markdown report
    md = ['# Pass 24: Byte-exact verification batch\n']
    md.append(f'Verified **{matched}/{len(final_results)}** mini-stub '
              f'functions byte-exact against original binaries using MASM '
              f'4.0 + DOSBox-X.\n')
    md.append('Refinement rounds: ' + ' → '.join(
        f"{h['matched']}/{h['total']}" for h in history) + '\n')
    md.append('| Module | Function | Match | Bytes | Note |')
    md.append('|---|---|---|---|---|')
    for r in final_results:
        ok = 'YES' if r['match'] else 'no'
        md.append(f"| `{r['module']}` | `{r['name']}` | {ok} | "
                  f"`{r['expected_hex']}` | {r['note']} |")
    (PASS24 / 'summary.md').write_text('\n'.join(md), encoding='utf-8')


if __name__ == '__main__':
    main()
