; ============================================================
; src/WINOLDAP/seg2_real.asm  --  AUTO-GENERATED by
;   bootstrap/disasm_to_masm.py
;
; Byte-exact MASM 4.00 source for segment 2 of original/WINOLDAP.MOD
; (1200 B). Capstone disassembly with iterative `db` fallback for
; instructions whose MASM 4.00 encoding differs from the shipped
; bytes. This file is verified byte-exact via
; bootstrap/analyze/verify_flat_com_via_masm.py.
; ============================================================

        .8086
WINOLDAP_SEG2 SEGMENT BYTE PUBLIC 'CODE'
        ASSUME cs:WINOLDAP_SEG2, ds:WINOLDAP_SEG2, ss:WINOLDAP_SEG2, es:WINOLDAP_SEG2

; -- data 0x0000..0x04AF (1200B) --
        db 00h, 00h, 00h, 00h, 05h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 43h, 50h, 00h, 00h, 0FFh, 0FFh, 00h, 00h, 00h, 00h, 08h, 00h, 08h, 00h, 00h, 00h
d_0020: db 34 DUP(0)
        db 02h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
d_0052: db 274 DUP(0)
        db 0FFh, 0FFh, 00h, 00h, 0FFh, 0FFh, 00h, 00h, 0FFh, 0FFh, 00h, 00h, 19h, 00h, 0F0h, 04h
        db 0FFh, 0FFh, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 10h, 00h, 08h, 00h
        db 0FFh, 0FFh, 00h, 00h, 02h, 00h, 00h, 04h, 0FFh, 0FFh, 00h, 00h, 00h, 00h, 00h, 00h
d_0194: db 238 DUP(0)
        db 0FFh, 0FFh, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 03h, 00h
        db 00h, 00h, 2Eh, 2Eh, 2Eh, 0FFh, 0FFh, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 0FFh, 0FFh, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
d_02B2: db 17 DUP(0)
        db 7Fh, 80h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 19h, 00h, 00h, 01h, 08h, 16h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 0FFh, 00h, 00h, 00h
d_02E3: db 268 DUP(0)
        db 0Ch, 0Bh, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
d_03FF: db 18 DUP(0)
        db 0F1h, 03h, 0F1h, 03h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h
        db 00h, 00h, 00h, 00h, 00h, 00h, 00h, 01h, 00h, 01h, 00h, 00h, 00h, 00h, 00h, 00h
d_0431: db 112 DUP(0)
        db 08h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h, 00h

WINOLDAP_SEG2 ENDS
        END
